### PR TITLE
Splitter and tabstrip visual improvements

### PR DESCRIPTION
**Pull request by HebaruSan**
## Problem

GUI has a vertical splitter between the mod list and the mod info pane and a horizontal splitter within one of the tabs of the mod info pane, but some users have found this to be non-obvious and ask whether information has been removed from the display (see #2412 and KSP-CKAN/NetKAN#6288).

The tab style chosen for the mod info pane is also a bit ugly and gray.

screenshot

splitter low splitter high

## Changes

Now each pane of these splitters has a minimum size:

- The mod info pane always has enough width for all of its tabs
- The top part of the metadata tab always has enough height for both of its fields
- The bottom part of the metadata tab always has enough height for its fields
- The vertical splitter itself is widened slightly to try to make it more obvious
  (I tried to enlarge the horizontal splitter as well, but setting the property had no effect.)

And the tabs are changed to a more conventional style, which also gives the tab pages a white background.

Minimum sizes of the panes illustrated:

image

### CODE REVIEW

**Comment by DasSkelett** [comment]
Can you push all labels in the lower part of metadata tab some Pixels down?
I think the Version text is sticking a bit to close to the splitter.

**Comment by politas** [comment]
Have you fixed it so the main splitter still works when tabs other than the mod details is shown? (An issue I noticed the other day but haven't had a chance to look at in detail, yet)

**Comment by HebaruSan** [comment]
I haven't consciously made any changes along those lines, but testing it out I don't see a problem with it either. I might not be understanding the issue though.

**Comment by politas** [comment]
Seems to work fine in this branch, so all good. I do note that the abstract is using the "Input Box" background colour, while the rest of the metadata is using the "Windows" background. Can we get them using the same style?
image

**Comment by HebaruSan** [comment]
@politas, that was to fix that control being _gray on white_ on Windows, which happened because it's a `RichTextBox` with `ReadOnly` set to true, and .NET and Mono apparently don't use the same colors for tabs. I've changed it to a `Label` and removed the color manipulation, so it should match the main background on both platforms now.

**Comment by politas** [comment]
Cool. The .Net/Mono promise of multi-platform UI development is not quite fulfilled, eh?

**Pull request merged**
