### PR TITLE
[incomplete] Mod roulette

### PR DESCRIPTION
**Pull request by martinnj**
Adds a mod roulette function to the CLI as described in #883.
Will run from both `ckan random n` and `ckan roulette n` where `n` is is an integer greater than 0.

TODO:
 - [ ] Solve conflict relationships properly.

### CODE REVIEW

**Comment by Postremus** [comment]
I tried ckan random 100. Got this error. ModuleManager is added twice in the recommends.

```
Do you want to install these mods? [Y/n] y
The following extra  have been recommended for the above selection:
 * TweakScale
 * Toolbar
 * FerramAerospaceResearch
 * ModuleManager
 * ModuleManager
 * AGExt
 * FilterExtensions
Do you want to install these mods as well? [Y/n] y
12775 [1] ERROR CKAN.RelationshipResolver (null) - Assertion failed: Adding Modu
leManager twice in relationship resolution

Unbehandelte Ausnahme: System.ArgumentException: Already contains module:ModuleM
anager
   bei CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
in c:\Users\Martin\Documents\Visual Studio 2013\Projects\CKAN\Core\Relationships
\RelationshipResolver.cs:Zeile 410.
   bei CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules) in c
:\Users\Martin\Documents\Visual Studio 2013\Projects\CKAN\Core\Relationships\Rel
ationshipResolver.cs:Zeile 195.
   bei CKAN.RelationshipResolver..ctor(IEnumerable`1 modules, RelationshipResolv
erOptions options, IRegistryQuerier registry, KSPVersion kspversion) in c:\Users
\Martin\Documents\Visual Studio 2013\Projects\CKAN\Core\Relationships\Relationsh
ipResolver.cs:Zeile 139.
   bei CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipR
esolverOptions options, IRegistryQuerier registry, KSPVersion kspversion) in c:\
Users\Martin\Documents\Visual Studio 2013\Projects\CKAN\Core\Relationships\Relat
ionshipResolver.cs:Zeile 123.
   bei CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOpti
ons options, IDownloader downloader) in c:\Users\Martin\Documents\Visual Studio
2013\Projects\CKAN\Core\ModuleInstaller.cs:Zeile 155.
   bei CKAN.CmdLine.Install.RunCommand(KSP ksp, Object raw_options) in c:\Users\
Martin\Documents\Visual Studio 2013\Projects\CKAN\Cmdline\Action\Install.cs:Zeil
e 105.
   bei CKAN.CmdLine.Roulette.RunCommand(KSP ksp, Object raw_options) in c:\Users
\Martin\Documents\Visual Studio 2013\Projects\CKAN\Cmdline\Action\Roulette.cs:Ze
ile 132.
   bei CKAN.CmdLine.MainClass.Main(String[] args) in c:\Users\Martin\Documents\V
isual Studio 2013\Projects\CKAN\Cmdline\Main.cs:Zeile 227.

C:\Users\Martin\Documents\Visual Studio 2013\Projects\CKAN\Cmdline\bin\Debug>
```

**Comment by Postremus** [comment]
"ckan roulette" just outputs the help, instead of doing the same as "ckan random"

**Comment by Postremus** [comment]
Roulette doesn't seem to check if a recommended mod is available for the instance's ksp version. I am on ksp 1.0.4. I got DeadlyReentry recommended, which does not exists yet for 1.0.4. Got this error:

```
The following mods have been randomly selected:
 * Hullcam VDS
 * GPOSpeedFuelPump
 * MOVAP
 * Real Solar System Textures - 8192 x 4096
 * Oblivion Aerospace
 * Kerbal Attachment System
 * KerboKatzUtilities
 * Modular Computer Package
 * FASA Launch Clamps and Towers
 * Portrait Stats
 * KAP Pack 1 - Early Tech
 * USI Tools
 * Kerbal Stats
 * EVA Handrails Pack Continued
 * Landing Height Display
 * Routine Mission Manager
 * AIES Aerospace
 * Spacetux Shared Assets
 * Transfer Window Planner
 * SmallFatTechnologies
Do you want to install these mods? [Y/n] y
The following extra  have been recommended for the above selection:
 * EditorExtensions
 * DeadlyReentry
Do you want to install these mods as well? [Y/n] y
Module DeadlyReentry required, but not listed in index, or not available for you
r version of KSP
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules
```

**Comment by pjf** [comment]
I'm skipping past this on my PR sweep because it's marked as incomplete, but I'd totally love a complete version to merge! <3

**Comment by martinnj** [comment]
I'm still on it, just need to figure out how to not select conflicting mods, thought it was solved, but when you increase the mod count they still mess up.

**Pull request closed without merging**
