### PR TITLE
Fixed protocol handler registration on linux (at least ubuntu)

### PR DESCRIPTION
**Pull request by Postremus**
Tested on Ubuntu 14.04
-If we have no existing mimeapps.list, create it
-start ckan with mono
-make the .desktop file executable
-correctly resolve the home Directory
-focus the mod we got in the modlist
related to #1433

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Does not work for me here on Arch Linux. I don't get a desktop file and it's not added to mimeapps.list. How do I enable logging?

**Comment by Postremus** [comment]
logging can only be activated with the Cmdline.exe, which will then start the gui:
Cmdline.exe --verbose
or
Cmdline.exe --debug

**Comment by SirCmpwn** [comment]
3926 [1] INFO CKAN.URLHandlers (null) - Trying to register URL handler
    3927 [1] INFO CKAN.URLHandlers (null) - Skipping URL handler: Parsing Error: Could not parse file ~/.local/share/applications/mimeapps.list

My mimeapps.list: https://sr.ht/Xz8G.txt

**Comment by SirCmpwn** [comment]
:+1: works for me, I just made a mistake when testing it.

**Comment by pjf** [comment]
Just checking if f81069e24cbf5cd5a8c5c22d065e5533ae551df1 is intentionally or accidentally on this branch. :)

**Comment by Postremus** [comment]
intentionally, because it also replaces some part of the url handler code.

**Comment by pjf** [comment]
@Postremus : Oh! That makes sense to me now. :) In the process of testing. :)

**Comment by pjf** [comment]
This works for me as well! Although if I've already got the CKAN open, then clicking on a `ckan://` link means I then have *two* (as opposed to the original being signalled somehow to change its focus).

Still, that's way better than what we had before, so I'm giving the code another glance over and then merging. Thank you very much! :)

**Pull request merged**
