### PR TITLE
Add download hashes to registry

### PR DESCRIPTION
**Pull request by plague006**
At some point they'll probably be needed client-side, and this gave me an excuse to poke around exactly how the registry is created.

### CODE REVIEW

**Comment by techman83** [comment]
Can you add a test for this change?

**Comment by hakan42** [comment]
Minor nitpick, could you name it "DownloadHashesDescriptor"? Adding a "e" to the plural?

**Comment by plague006** [comment]
Typo corrected for the class name. Adding a test will take a little longer... Namely I'll have to find a tutorial on what they are and how to write them.

**Comment by techman83** [comment]
@plague006 You should be able to add the Download_Hash data to the test data [here](https://github.com/KSP-CKAN/CKAN/blob/master/Tests/Data/TestData.cs#L274) and then do the asserts [here](https://github.com/KSP-CKAN/CKAN/blob/master/Tests/Core/Types/Module.cs#L34).

**Comment by plague006** [comment]
Thanks @techman83. Haven't had the time to learn up, but can follow instructions and copy+paste like a pro. :D

**Comment by pjf** [comment]
I can't see a reason not to add this, and since I'm bumping the release number for tonight with all the spec changes, this makes a great time to do so.

Tested everything is good, merging now.

**Pull request merged**
