### PR TITLE
Add "Filter by description" to GUI

### LINKED ISSUE #1631: Add Filter by description to GUI
Steven Mading on the forums [spake thusly](http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1161-13-mar-2016/&do=findComment&comment=2456148):

> CKAN is great if you already know about the available mods and what they do, but it's not so great for browsing mods because you can only really search based on the mod's name.

> Are there any plans to improve the ability to *find* a mod you like, either by adding 'tags' fields that authors can populate, or by just making a sort of 'dumb grep' on the mods' description fields?  I would actually prefer a dumb grep, with the expectation that authors can add a keyword list to the end of their description to help searching, than searching ONLY on keywords the author picked and not on their description text.

This seems like a reasonable suggestion to me, and most of the required code is presumably basically already there, it just needs to be adapted to a different field.

### PR DESCRIPTION
**Pull request by politas**
Adds new UI elements, rearranges others somewhat. Allows users to search for text strings in mod abstracts (called "description" in the UI)

The proposed UI changes can be seen here: https://dl.dropboxusercontent.com/u/10499401/FilterbyDescriptionUIChange.png

Tests run: 366, Errors: 0, Failures: 0, Inconclusive: 0, Time: 10.3875286 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Closes #1631

### CODE REVIEW

**Comment by pjf** [comment]
Oooh, this looks really sensible! Reviewing now.

**Comment by pjf** [comment]
Looks great, tests great, merging now.

**Comment by pjf** [comment]
Merged with great thanks! :)

**Comment by Dazpoet** [comment]
Was I the only one who read "tests great" as "tastes great"?

**Pull request merged**
