### PR TITLE
Update Spec.md

### LINKED ISSUE #1770: Please clarify install_to in the Spec
At least i did not understand what paths are OK to put in install_to correctly. I thought it would only be these

> Valid values for this entry are GameData, Ships, Ships/SPH(v1.12), Ships/VAB(v1.12), Ships/@thumbs/VAB(v1.16), Ships/@thumbs/SPH(v1.16), Tutorial, Scenarios (v1.14) and GameRoot (which should be used sparingly, if at all)

but i am told some subdirectories are OK, too.  

Please clarify the install_to section because maybe it is  not just me being stupid.

### PR DESCRIPTION
**Pull request by politas**
An attempt to clarify the install_to options.
Closes #1770

### CODE REVIEW

**Comment by plague006** [comment]
If you change

```specified under `GameData` *only* (**v1.2**)```
to
```specified only under `GameData` (**v1.2**)```
you maintain the same meaning while also having the spec_version number more clearly attached to `GameData`.

I would also suggest maintaining the line break that previously existed as it now appears as a hard-to-parse blob of text. http://puu.sh/peweI/370e4d780b.png

**Comment by politas** [comment]
I really disliked the line break, since this information should be in the context of the "install_to" bullet point. The separate paragraph broke that connection.

**Comment by politas** [comment]
I really wish there was a way to do second-level bullet points.

**Comment by dbent** [comment]
- One
  - Two
    - Three?

**Comment by politas** [comment]
Ah, like that! Much better.

**Comment by plague006** [comment]
Looks good to me, merging with my thanks.

**Pull request merged**
