### PR TITLE
Bulk (de-)selection features

### PR DESCRIPTION
**Pull request by martinnj**
Menu items added for deslecting all, or selecting installed. Checkbox
added to recommendations page to toggle all recommended/suggested mods.

### CODE REVIEW

**Comment by pjf** [comment]
@martinnj : I'm *so* sorry this has gone unmerged for so long. I've been travelling, which has put a dint in my availability, and I know that a number of the other devs have had similarly hectic schedules.

I don't suppose I can ask you to merge or rebase from master? I know that your knowledge of how to resolve the merge conflicts will be far superior to mine. :)

Many, many thanks, and keep being amazing!

~ Paul

**Comment by pjf** [comment]
Also linking #1211, as I presume this is #1211:TNG. :)

**Comment by martinnj** [comment]
Everyone deserves some time off for a summer holiday, so no worries.
I'll look into getting a rebase done, never really got them, so might take a little.

**Comment by martinnj** [comment]
@pjf : Should be all ready to merge again.

**Comment by martinnj** [comment]
Solved more merge conflicts.

**Pull request closed without merging**
