### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Olympic1**

### CODE REVIEW

**Comment by HebaruSan** [comment]
There are a _lot_ of semantically non-meaningful changes in these diffs. Any suggestions for ways to view just the actual changed strings?

**Comment by Olympic1** [comment]
It didn't do this before and I only changed the repo where it pulls the files from. I'll check into it

**Comment by HebaruSan** [comment]
Sounds good. For what it's worth, I wouldn't consider it a deal-breaker if we can't do anything about it, and my concerns are:

- Having commits in the log that say "New translations" when they are just reformats of the same adata
- Accidentally losing or changing a string that we didn't know was being affected in this giant sea of changes

If I could run some kind of "XML diff" command and just see the which strings will look different in the UI after this, that would be good enough. I looked for such a command and surprisingly could not find one.

**Comment by HebaruSan** [comment]
I finally gave up and wrote a short shell script for this. I'll commit it to this branch so we have it in case we need it again, along with a rebase and some minor clean-up of the changes. Here's the output:

```
Cmdline/Properties/Resources.fr-FR.resx
--- master
+++ HEAD
@@ -696,0 +697,5 @@
+  <data name="CompletionNotAvailable" xml:space="preserve">
+    <value>
+Aucune instance de jeu sélectionnée, complétion de l'identifiant indisponible.
+Utilisez la commande `instance default` pour choisir une instance.</value>
+  </data>

ConsoleUI/Properties/Resources.fr-FR.resx
--- master
+++ HEAD
@@ -694,0 +695,6 @@
+  <data name="ModListFilterMenu" xml:space="preserve">
+    <value>Filtres d'installation...</value>
+  </data>
+  <data name="ModListFilterMenuTip" xml:space="preserve">
+    <value>Modifier la liste des fichiers et dossiers à exclure de l'installation</value>
+  </data>
@@ -801,0 +808,24 @@
+  </data>
+  <data name="FiltersTitle" xml:space="preserve">
+    <value>Filtres d'Installation</value>
+  </data>
+  <data name="FiltersAddMiniAVCMenu" xml:space="preserve">
+    <value>Ajouter MiniAVC</value>
+  </data>
+  <data name="FiltersAddMiniAVCMenuTip" xml:space="preserve">
+    <value>Empêcher MiniAVC d'être installé</value>
+  </data>
+  <data name="FiltersGlobalHeader" xml:space="preserve">
+    <value>Filtres Globaux</value>
+  </data>
+  <data name="FiltersInstanceHeader" xml:space="preserve">
+    <value>Filtres de l'Instance</value>
+  </data>
+  <data name="FilterAddGhostText" xml:space="preserve">
+    <value>&lt;Entrez un filtre&gt;</value>
+  </data>
+  <data name="FilterAddAcceptTip" xml:space="preserve">
+    <value>Accepter cette value</value>
+  </data>
+  <data name="FilterAddTitle" xml:space="preserve">
+    <value>Ajouter un Filtre</value>

GUI/Localization/de-DE/AskUserForAutoUpdatesDialog.de-DE.resx
--- master
+++ HEAD
@@ -48,0 +49 @@
+  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"/>

GUI/Localization/fr-FR/CloneFakeGameDialog.fr-FR.resx
--- master
+++ HEAD
@@ -68 +68 @@
-    <value>Version:</value>
+    <value>Version :</value>

GUI/Localization/fr-FR/CompatibleGameVersionsDialog.fr-FR.resx
--- master
+++ HEAD
@@ -80 +80 @@
-    <value>Installation:</value>
+    <value>Installation :</value>

GUI/Localization/fr-FR/EditModSearchDetails.fr-FR.resx
--- master
+++ HEAD
@@ -80 +80 @@
-    <value>Compatible:</value>
+    <value>Compatible :</value>

GUI/Localization/fr-FR/EditModpack.fr-FR.resx
--- master
+++ HEAD
@@ -57,0 +58,3 @@
+  <data name="AuthorLabel.Text" xml:space="preserve">
+    <value>Auteur:</value>
+  </data>
@@ -59 +62 @@
-    <value>Version:</value>
+    <value>Version :</value>
@@ -65 +68 @@
-    <value>Licence:</value>
+    <value>Licence :</value>

GUI/Localization/fr-FR/GameCommandLineOptionsDialog.fr-FR.resx
--- master
+++ HEAD
@@ -51 +51 @@
-    <value>Arguments:</value>
+    <value>Arguments :</value>

GUI/Localization/fr-FR/Main.fr-FR.resx
--- master
+++ HEAD
@@ -117,0 +118,3 @@
+  <data name="discordToolStripMenuItem.Text" xml:space="preserve">
+    <value>Discord</value>
+  </data>
@@ -176,0 +180,6 @@
+  </data>
+  <data name="viewPlayTimeStripMenuItem.Text" xml:space="preserve">
+    <value>Temps de jeu...</value>
+  </data>
+  <data name="minimizeNotifyIcon.Text" xml:space="preserve">
+    <value>CKAN</value>

GUI/Localization/fr-FR/ManageMods.fr-FR.resx
--- master
+++ HEAD
@@ -69,0 +70,3 @@
+  <metadata name="InstallSize.UserAddedColumn" type="System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
+    <value>True</value>
+  </metadata>
@@ -164,0 +168,3 @@
+  </data>
+  <data name="InstallSize.HeaderText" xml:space="preserve">
+    <value>Installer</value>

GUI/Localization/fr-FR/NewRepoDialog.fr-FR.resx
--- master
+++ HEAD
@@ -63 +63 @@
-    <value>URL</value>
+    <value>Lien</value>

GUI/Localization/fr-FR/NewUpdateDialog.fr-FR.resx
--- master
+++ HEAD
@@ -51 +51 @@
-    <value>Version:</value>
+    <value>Version :</value>

GUI/Localization/fr-FR/PlayTime.fr-FR.resx
--- master
+++ HEAD
@@ -48,0 +49,3 @@
+  <data name="EditHelpLabel.Text" xml:space="preserve">
+    <value>Pour modifier, sélectionnez une valeur et commencez à taper ou appuyez sur F2</value>
+  </data>

GUI/Localization/fr-FR/SettingsDialog.fr-FR.resx
--- master
+++ HEAD
@@ -177 +177 @@
-    <value>URL</value>
+    <value>Lien</value>

GUI/Localization/fr-FR/Wait.fr-FR.resx
--- master
+++ HEAD
@@ -54,0 +55,3 @@
+  <data name="OkButton.Text" xml:space="preserve">
+    <value>OK</value>
+  </data>

GUI/Localization/ja-JP/ManageMods.ja-JP.resx
--- master
+++ HEAD
@@ -69,0 +70,3 @@
+  <metadata name="InstallSize.UserAddedColumn" type="System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
+    <value>True</value>
+  </metadata>
@@ -164,0 +168,3 @@
+  </data>
+  <data name="InstallSize.HeaderText" xml:space="preserve">
+    <value>インストール</value>

GUI/Localization/ko-KR/Main.ko-KR.resx
--- master
+++ HEAD
@@ -183,0 +184,3 @@
+  <data name="minimizeNotifyIcon.Text" xml:space="preserve">
+    <value>CKAN</value>
+  </data>

GUI/Localization/ko-KR/ManageMods.ko-KR.resx
--- master
+++ HEAD
@@ -67 +67,4 @@
-  <metadata name="SizeCol.UserAddedColumn" type="System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
+  <metadata name="DownloadSize.UserAddedColumn" type="System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
+    <value>True</value>
+  </metadata>
+  <metadata name="InstallSize.UserAddedColumn" type="System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
@@ -163 +166 @@
-  <data name="SizeCol.HeaderText" xml:space="preserve">
+  <data name="DownloadSize.HeaderText" xml:space="preserve">
@@ -164,0 +168,3 @@
+  </data>
+  <data name="InstallSize.HeaderText" xml:space="preserve">
+    <value>설치</value>

GUI/Localization/pt-BR/SelectionDialog.pt-BR.resx
--- master
+++ HEAD
@@ -53 +53 @@
-    <value>Selecione</value>
+    <value>Selecionar</value>

GUI/Localization/ru-RU/ManageMods.ru-RU.resx
--- master
+++ HEAD
@@ -69,0 +70,3 @@
+  <metadata name="InstallSize.UserAddedColumn" type="System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
+    <value>True</value>
+  </metadata>
@@ -164,0 +168,3 @@
+  </data>
+  <data name="InstallSize.HeaderText" xml:space="preserve">
+    <value>Установить</value>

GUI/Localization/zh-CN/EditModSearchDetails.zh-CN.resx
--- master
+++ HEAD
@@ -49,8 +49,2 @@
-  <metadata name="menuStrip2.TrayLocation" type="System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
-    <value>236, 17</value>
-  </metadata>
-  <metadata name="ModListContextMenuStrip.TrayLocation" type="System.Drawing.Point, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
-    <value>351, 17</value>
-  </metadata>
-  <data name="$this.Localizable" type="System.Boolean, mscorlib">
-    <value>True</value>
+  <data name="FilterByNameLabel.Text" xml:space="preserve">
+    <value>按Mod名称筛选:</value>
@@ -60,3 +53,0 @@
-  </data>
-  <data name="FilterByNameLabel.Text" xml:space="preserve">
-    <value>按Mod名称筛选:</value>

GUI/Localization/zh-CN/Wait.zh-CN.resx
--- master
+++ HEAD
@@ -54,0 +55,3 @@
+  <data name="OkButton.Text" xml:space="preserve">
+    <value>确认</value>
+  </data>
```

**Comment by HebaruSan** [comment]
- Added `bin/git-xml-diff.sh`, run it to print only significant changes to .resx files between master and HEAD
- Several of the languages had extra copies of various icons, now removed, which will save about 800 KiB in ckan.exe
- The `<assembly>` tags are not needed and are removed
- The `<metadata>` tags are not needed and are removed

**Review by HebaruSan — APPROVED** [review]
Confirmed that there are no deterimental significant changes using the `bin/git-xml-diff.sh` script. :tada:

Let's merge this to keep up to date with Crowdin.

**Pull request merged**
