### PR TITLE
Fix two small typos in Resources.pt-BR.resx at line 182

### PR DESCRIPTION
**Pull request by idrkwhattoput**
Fixed small typos in line 182 (appears when the user tries to install a mod in a non-supported KSP version).

accidentaly discovered this when i was trying to install a mod, so here it is 👍

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks for the update! Was the other change intentional? The old text "mantenedores" seems to be a closer fit to the English "maintainers" than "colaboradores".

Also FYI that there's an easier way to edit these nowadays:  https://crowdin.com/project/ckan

**Comment by idrkwhattoput** [comment]
> Hi @idrkwhattoput, thanks for the update! Was the other change intentional? The old text "mantenedores" seems to be a closer fit to the English "maintainers" than "colaboradores".
> 
> Also FYI that there's an easier way to edit these nowadays: https://crowdin.com/project/ckan

hello, yes the other change was intentional it maked more sense for me to put "colaboradores" instead of "mantenedores" im also looking out to help with the translation so thanks for the link

**Comment by HebaruSan** [comment]
> it maked more sense for me to put "colaboradores" instead of "mantenedores"

@idrkwhattoput, thanks, would you mind saying why you think that? As I mentioned earlier, "mantenedores" gives an exact match to the English translation when I put it into a translator.

**Comment by idrkwhattoput** [comment]
> > it maked more sense for me to put "colaboradores" instead of "mantenedores"
> 
> @idrkwhattoput, thanks, would you mind saying why you think that? As I mentioned earlier, "mantenedores" gives an exact match to the English translation when I put it into a translator.

Hmmm, well then sorry i never heard the word "mantenedores" when speaking Brazilian Portuguese 😅 so i thought it was incorrect.

**Comment by idrkwhattoput** [comment]
finished

**Comment by HebaruSan** [comment]
Please don't close this. We need it to be open so we can merge your fixes into the main branch.

**Comment by idrkwhattoput** [comment]
ph sorry didnt know

**Review by HebaruSan — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
