### PR TITLE
Adding Simplified Chinese Localization 

### PR DESCRIPTION
**Pull request by 050644zf**

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks, this is great! One file seems to be missing. Would you mind taking a look?

https://github.com/KSP-CKAN/CKAN/blob/master/GUI/Main/Main.resx

**Comment by 050644zf** [comment]
Thanks for notifying, I added that file

**Comment by HebaruSan** [comment]
Pasting from Discord:

screenshot

**Comment by HebaruSan** [comment]
Mine looks the same except the "X files" string is translated, I think thanks to the addition of `Main.zh-CN.resx`:

image

**Comment by HebaruSan** [comment]
## Test build for volunteer proofreaders

- [ckan.zip](https://github.com/KSP-CKAN/CKAN/files/4277625/ckan.zip)

### Switching to Chinese

1. Launch CKAN
2. Settings &rarr; CKAN settings
3. Under "More Settings", change the Language field to zh-CN
4. Close CKAN
5. Launch again; you should now see Chinese characters

### Testing

Try to view every screen and read every piece of text. For example, a non-exhaustive list:

- Read all the menus
- Inspect the mod info pane on the right side
- Install a mod
  - With recommendations
  - With dependencies provided by multiple modules (e.g. Scatterer)
- Edit the settings
- Select / add / remove game instances
- Set the compatible KSP versions
- Export a modpack
- Import a modpack
- Anything else you can think of

### Feedback

Please post a reply here with anything that doesn't look right or could be improved. Or even if you have questions or want to discuss.

Many strings will still be in English! In most cases this is because CKAN is divided into "Core" and "GUI" parts, and only the GUI is translated, while Core is English-only. In a few cases it *might* be because a GUI string was missed. Unfortunately there's no easy way to tell which is which, but if you ask, we can figure it out.

Remember that not everyone here can read Chinese (e.g., I can't), so comments about recommended changes should be specific enough that we can figure out what you're talking about. For example, a screenshot will be most useful if you draw a red circle around a problem.

**Comment by HebaruSan** [comment]
@050644zf, do you know of a Chinese-language forum for KSP where users might be interested in giving feedback on this translation? I posted on the main CKAN thread, but @DasSkelett thinks that Chinese-language users might primarily be located in other places.

**Comment by HebaruSan** [comment]
> Mine looks the same

Hmm, not quite:

image image

image image

image image

image image

image image

I wonder if those are caused by missing glyphs, bad wrapping, something else?

**Comment by 050644zf** [comment]
```
未经处理的异常:  System.ArgumentException: 类型“System.Globalization.CalendarId[]”的对象无法转换为类型“System.Int32[]”。
   在 System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   在 System.Reflection.RtFieldInfo.UnsafeSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   在 System.Runtime.Serialization.FormatterServices.SerializationSetValue(MemberInfo fi, Object target, Object value)
   在 System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   在 System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   在 System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   在 System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   在 System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   在 System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   在 System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   在 System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   在 System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   在 System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   在 System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   在 System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   在 CKAN.Main.InitializeComponent()
   在 CKAN.Main..ctor(String[] cmdlineArgs, KSPManager mgr, Boolean showConsole)
   在 CKAN.GUI.Main_(String[] args, KSPManager manager, Boolean showConsole)
   在 CKAN.CmdLine.MainClass.Gui(KSPManager manager, GuiOptions options, String[] args)
   在 CKAN.CmdLine.MainClass.RunSimpleAction(Options cmdline, CommonOptions options, String[] args, IUser user, KSPManager manager)
   在 CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   在 CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by HebaruSan** [comment]
Oh right, my Linux install still has Mono 6, which can't build binaries that work on Windows.
One moment, I'll make a replacement...

**Comment by 050644zf** [comment]
And as for Chinese forum, yes we have some forum like tieba, bilibili, etc. I would like to post the test in our discord-like group first.

**Comment by HebaruSan** [comment]
OK, a new ZIP is now linked above which should not throw that exception.

**Comment by 050644zf** [comment]
Alright, I've posted Localization test in our group.

**Comment by tinygrox** [comment]
image
Too ugly.
Recommended change to "自动安装"
😃

**Comment by HebaruSan** [comment]
Pasting discussion from Discord for convenience:

image

As noted, the characters do not all fit into their allotted space, which we'll need to fix before merging. I can't tell the difference without a reference because I am not familiar with the characters, but it is easy enough to adjust the sizes as needed.

**Comment by HebaruSan** [comment]
Checklist while comparing the app to the resx files...

- [x] File menu looks fine; skipping other menus and dropdowns since I think their size is auto-managed by Windows
- [x] About window looks fine
- [x] Toolbars look fine
- [x] Tabstrip looks good
- [x] Changeset tab page looks fine
- [x] Mod info looks good
- [x] Choose provided mods tab page looks fine
- [x] Progress tab page looks OK
- [x] Choose recommended mods tab page is good
- [x] Delete directories tab page is OK
- [x] Plugins dialog looks good
- [x] Manage instances dialog is fine
  - [x] Clone/fake instance dialog is fine
- [x] Compatible versions dialog is good
- [x] Settings looks fine, somehow (!)
  image
- [x] New repo dialog looks fine

Found a few untranslated strings:

image

image

image

Label on the Edit Labels window overlaps the dropdown:

image

And a few dialogs with bad sizes (pre-existing issue):

image

image

**Comment by HebaruSan** [comment]
The untranslated strings **do** have translations in the .zh-CN.resx files. I think "No available updates" is a case of trying to update a GUI property from a background thread, easily fixed. The progress tab page titles are a mystery, though. `System.Console.WriteLine` reports that we are passing English language strings to `tabController.RenameTab`. Figure that one out...

**Comment by HebaruSan** [comment]
Pushed a commit with fixes for the problems in my previous comment.

Since I'm not able to reproduce the issue with 1-2 pixels missing on some characters, I won't be able to work on addressing that. @050644zf, can you try editing the sizes yourself? They should all be in the .Designer.cs files, like this:

https://github.com/KSP-CKAN/CKAN/blob/d0b3f834bbde62483333bc9883b1d0f295864348/GUI/Dialogs/SettingsDialog.Designer.cs#L397

It should be fine to make them slightly larger for all languages.

**Comment by 050644zf** [comment]
@HebaruSan Now I edited the size to (112,25), comparing to the unmodified button, it does show the hidden pixel.

**Comment by HebaruSan** [comment]
Cool, if that size works then we can make all the buttons that big. Are there still any problems with the Settings dialog that you can see?

**Comment by 050644zf** [comment]
> Cool, if that size works then we can make all the buttons that big. Are there still any problems with the Settings dialog that you can see?

I think there is no problem now.

**Comment by HebaruSan** [comment]
Excellent! I think this looks great now, will merge shortly...

**Pull request merged**
