### PR TITLE
Purge stale cache entries for SpaceDock

### PR DESCRIPTION
**Pull request by HebaruSan**
This is #2337, but for SpaceDock.

Needs KSP-SpaceDock/SpaceDock#195 to be merged to SpaceDock's production. Currently it's still being tested on the alpha server.

### CODE REVIEW

**Comment by HebaruSan** [comment]
The SD change has advanced from the alpha to the beta server.

https://beta.spacedock.info/api/mod/2

`{"name": "netkan", "id": 2, "game": "Kerbal Space Program", "game_id": 1, "short_description": "The EXE that CKAN uses to inflate metadata", "downloads": 0, "followers": 0, "author": "HebaruSan", "default_version_id": 2, "shared_authors": [{"username": "DasSkelett", "description": " ", "forumUsername": "DasSkelett", "ircNick": "DasSkelett", "twitterUsername": "DasSkelett ", "redditUsername": ""}], "background": null, "bg_offset_y": null, "license": "MIT", "website": "", "donations": "", "source_code": "", "url": "/mod/2/netkan", "versions": [{"friendly_version": "v1.26.78fec44d2ad73", "game_version": "1.8.1", "id": 2, "created": "2020-01-24T00:09:33.066554", "download_path": "/mod/2/netkan/download/v1.26.78fec44d2ad73", "changelog": null}], "description": "Just a junk file for testing.", "description_html": "<p>Just a junk file for testing.</p>"}`

**Comment by techman83** [comment]
Is that a field that could be used for #2916 ?

**Comment by HebaruSan** [comment]
Yes, I suppose so.

**Comment by HebaruSan** [comment]
It's in production!

https://spacedock.info/api/mod/10

`... "created": "2020-02-13T14:43:30.329419", ...`

**Comment by DasSkelett** [comment]
Looks good, already had an effect:
https://github.com/KSP-CKAN/CKAN-meta/commit/b52717ce21cbdaed8235c4c6f2d38508ef075403

**Pull request merged**
