### PR TITLE
Search in the previous stanza for the required mod

### LINKED ISSUE #1097: TooManyProvides generated even when an exact mod later in a depends list satsifies it
Hey,

just wanted to get my mods installed on another machine.  
Used the new export feature for this.  
Using on both machines ckan 1.6.22 on windows 8.1, ksp 1.0.2

mod list: http://puu.sh/ijJz3/2d985dcfba.ckan

Exception:
```
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
CKAN.TooManyModsProvideKraken: Too many mods provide AstronomersPack-Clouds:
AstronomersPack-Clouds-High Interstellar.V2
* AstronomersPack-Clouds-Low Interstellar.V2
* AstronomersPack-Clouds-Medium Interstellar.V2
   bei CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, Relationship reason, RelationshipResolverOptions options, Boolean soft_resolve)
   bei CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options)
   bei CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, Relationship reason, RelationshipResolverOptions options, Boolean soft_resolve)
   bei CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions options)
   bei CKAN.RelationshipResolver..ctor(ICollection`1 modules, RelationshipResolverOptions options, Registry registry, KSPVersion kspversion)
   bei CKAN.Main.InstallList(HashSet`1 toInstall, RelationshipResolverOptions options, NetAsyncDownloader downloader)
   bei CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34014 built by: FX45W81RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
ckan
    Assembly-Version: 0.0.0.0.
    Win32-Version: 0.0.0.0.
    CodeBase: file:///C:/Users/panze_000/Desktop/ckan.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34250 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34239 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34230 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.36213 built by: FX452RTMLDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Microsoft.GeneratedCode
    Assembly-Version: 1.0.0.0.
    Win32-Version: 4.0.30319.34230 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Transactions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34230 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.EnterpriseServices
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.33440 built by: FX45W81RTMREL.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.0.30319.34209 built by: FX452RTMGDR.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle Ausnahmefehler an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.



```

### PR DESCRIPTION
**Pull request by Postremus**
fixes #1097

### CODE REVIEW

**Comment by Postremus** [comment]
fixes #1274

**Comment by pjf** [comment]
Best pull request number ever. :)

**Comment by pjf** [comment]
This is really clever, thank you.

Notes for myself:

- If we were going to throw a TooManyProvides, we instead check to see if the parent stanza of the same relation to see if that has a solution. For example, if A depends upon B and C, B depends upon X, and C provides X, then we're golden rather than krakening.
- This doesn't check grandparent, sibling, or cousin stanzas, so we may still end up with a TMP even when there would have only been a single solution, but we're still oodles better than we are without this change.
- This should mostly work for the situation where we're dealing with exported modlists, as all the dependent/recommended mods are in the top-level list. (But theoretically we could have A depends upon B which depends D which depends upon X...)

I'm about to dash to lunch, but will be testing/merging this after I'm back.

**Comment by pjf** [comment]
Tested with a hacked version of @Postremus' modlist (below).

1. Without the patch we ask for the user to select an option for `AstronomersPack-Clouds` (cmdline) or hang (what's up with that?)
1. With the patch, we automatically select the clouds from the modlist, and we install (both GUI and cmdline).

I'm doing another once over of the code, and then merging. :)

```
{
	"kind": "metapackage",
	"abstract": "A list of modules installed on the default KSP instance",
	"name": "installed-default",
	"license": "unknown",
	"identifier": "installed-default",
	"spec_version": "v1.6",
        "version" : "1",
	"depends": [
		{
			"name": "QuickScroll"
		},
		{
			"name": "ModuleManager"
		},
		{
			"name": "ScienceAlert"
		},
		{
			"name": "KerbalEngineerRedux"
		},
		{
			"name": "ContractConfigurator"
		},
		{
			"name": "AlternateResourcePanel"
		},
		{
			"name": "AeroGUI"
		},
		{
			"name": "AstronomersPack"
		},
		{
			"name": "AstronomersPack-DistantObjectEnhancement"
		},
		{
			"name": "DistantObject"
		},
		{
			"name": "AstronomersPack-PlanetShine"
		},
		{
			"name": "PlanetShine"
		},
		{
			"name": "AstronomersPack-Clouds-Medium"
		},
		{
			"name": "EnvironmentalVisualEnhancements"
		},
		{
			"name": "AstronomersPack-AtmosphericScattering"
		},
		{
			"name": "AstronomersPack-Auroras-4K"
		},
		{
			"name": "AstronomersPack-Sandstorms"
		},
		{
			"name": "AstronomersPack-Snow"
		},
		{
			"name": "AstronomersPack-SurfaceGlow"
		},
		{
			"name": "KerbalKonstructs"
		},
		{
			"name": "KerbalAlarmClock"
		},
		{
			"name": "MenuStabilizer"
		},
		{
			"name": "ContractConfigurator-RemoteTech"
		},
		{
			"name": "RemoteTech"
		},
		{
			"name": "SmokeScreen"
		},
		{
			"name": "KlockheedMartian-Gimbal"
		},
		{
			"name": "ContractConfigurator-UnmannedContracts"
		},
		{
			"name": "SpaceShuttleEngines"
		},
		{
			"name": "WaypointManager"
		},
		{
			"name": "ContractsWindowPlus"
		},
		{
			"name": "StockBugFixModules"
		},
		{
			"name": "ContractConfigurator-Tourism"
		},
		{
			"name": "SpacetuxSA"
		},
		{
			"name": "CoherentContracts"
		},
		{
			"name": "SpaceY-Lifters"
		},
		{
			"name": "ContractConfigurator-AnomalySurveyor"
		},
		{
			"name": "ContractConfigurator-InitialContracts"
		},
		{
			"name": "ContractConfigurator-AdvancedProgression"
		},
		{
			"name": "ContractConfigurator-GrandTours"
		},
		{
			"name": "InterstellarFuelSwitch-Core"
		},
		{
			"name": "TACLS"
		},
		{
			"name": "TACLS-Config-Stock"
		},
		{
			"name": "ContractConfigurator-KerbinSideJobs"
		},
		{
			"name": "VenStockRevamp"
		},
		{
			"name": "CrowdSourcedScience"
		},
		{
			"name": "KDEX"
		},
		{
			"name": "SolarScience"
		},
		{
			"name": "EngineLighting"
		},
		{
			"name": "FirespitterCore"
		},
		{
			"name": "AlcubierreStandalone"
		},
		{
			"name": "SeriousKerbalBusiness"
		},
		{
			"name": "KerbinSide"
		},
		{
			"name": "UniversalStorage"
		},
		{
			"name": "CommunityResourcePack"
		},
		{
			"name": "OuterPlanetsMod"
		},
		{
			"name": "NearFutureSpacecraft"
		},
		{
			"name": "TransferWindowPlanner"
		},
		{
			"name": "TarsierSpaceTechnologyWithGalaxies"
		},
		{
			"name": "RasterPropMonitor-Core"
		},
		{
			"name": "NearFutureSolar"
		},
		{
			"name": "ContractConfigurator-KerbinSpaceStation"
		},
		{
			"name": "NearFutureConstruction"
		},
		{
			"name": "NearFutureProps"
		},
		{
			"name": "StockClamshellFairings"
		},
		{
			"name": "KAS"
		},
		{
			"name": "KIS"
		},
		{
			"name": "ContractConfigurator-FieldResearch"
		},
		{
			"name": "xScience"
		},
		{
			"name": "Impact"
		},
		{
			"name": "NearFuturePropulsion"
		},
		{
			"name": "NearFutureElectrical"
		},
		{
			"name": "NearFutureElectrical-Core"
		},
		{
			"name": "KerbalAircraftExpansion"
		},
		{
			"name": "FirespitterResourcesConfig"
		}
	]
}
```

**Pull request merged**
