### PR TITLE
Minimize CKAN to tray and automatic refreshing

### LINKED ISSUE #2377: [Suggestion] CKAN in the System Tray & CKAN/Mod Update Notifier
_This is not a issue and yes a suggestioni so i think don't need the issue layout when open a new issue (I think, if i wrong tell me and i fix it)_

This is a idea i have, while waiting to mods get updated (And opening some times) to CKAN.
This is not a **_really_** important feature is just a good util, you can put in low priority if you want or you can tell for yourself "Do it! Just do it!!" (old meme reference xD)

How work:
System Tray - Method 1:
If you click in the "X" (To close the program) instead of him close he minimizes to the System Tray and to show again just click in the icon and to close him, right-click in the icon>Exit or close normally File>Exit or Ctrl + Q (Shortcut)
Method 2:
Add a new button in the left of "Minimize button" or in the right of "X" (Good for not close the CKAN instead of minimize him by mistake) to minimize to System Tray and close same of Method 1.
Notification
Show a info box in the screen talking the mod name, version installed and the new version available and the same if is a CKAN and for blind (Like i xD) can make a sound. Note: I really like if while in fullscreen (Games and video player, web and app) the notification don't minimized the game to desktop and players to show the task bar because this already happen with me and this is really annoying (The notification sound is useful to this situation).

Images i made by editing for exemples:
System Tray - Method 1 (Can have others options if you want, this is just a options exemple)
[](https://postimg.org/image/arczdc4kd/)
System Tray - Method 2
Left
[](https://postimg.org/image/3u9m9gyot/)
Right
[](https://postimg.org/image/e70i93uel/)
Notification
[](https://postimg.org/image/k0f5niqbx/)

### PR DESCRIPTION
**Pull request by Olympic1**
### Core
Added an automatic refreshing of CKAN that happens after N minutes. This option can be set via the settings menu and is stored in the windows registry. This behaviour starts when the GUI is loaded and can be paused via the respective options, or by setting the rate to `0`.

### GUI
The GUI settings window's updates section is halved and a new behaviour section is added next to it to save some space:

settingswindow

* The `Enable tray icon` shows a CKAN icon in the tray. The window is still shown on the taskbar.
* The `Minimize to tray` allows minimizing to the tray. The window is hidden from the taskbar.
* The refresh rate to set an interval in minutes to refresh the modlist automatically.
* The `pause refreshing` pauses the automatic refreshing. This is disabled when `RefreshRate` is set to `0`.

When the GUI is minimized, you can double click the icon to bring back the GUI.  
Also right clicking the icon shows a menu:

traymenu

* The updates option shows the amount of available updates. This is disabled when none are available and is clickable when there are. Clicking the option selects all of the available updates.
* `Refresh` refreshes the modlist
* `Pause` pauses the automatic refreshing. This is disabled when `RefreshRate` is set to `0`.
* `Open CKAN` opens the GUI
* `Open KSP Directory` opens the current KSP directory
* `CKAN Settings` opens the settings menu
* `Quit` closes CKAN

When an update becomes available, it pops up a balloon notifying you that there is an update. Clicking it installs it. (Thanks @HebaruSan)

### Other
* Removed a duplicate `StartPosition` in the settings window
* Redone the tab order in the settings window
* Moved `Refresh on startup` from updates to more settings

Closes #2377.

### CODE REVIEW

**Comment by ReiDaTecnologia** [comment]
Thanks for taking you time and effort in my suggestion and i really hope this PR get accepted!

**Comment by HebaruSan** [comment]
I get this on trying to open the settings on Windows:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Main.UpdateRefreshTimer()
   at CKAN.SettingsDialog.UpdateRefreshRate()
   at CKAN.SettingsDialog.RefreshTextBox_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.TextBoxBase.set_Text(String value)
   at System.Windows.Forms.TextBox.set_Text(String value)
   at CKAN.SettingsDialog.UpdateRefreshRate()
   at CKAN.SettingsDialog.UpdateDialog()
   at CKAN.SettingsDialog.SettingsDialog_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by HebaruSan** [comment]
If you open CKAN, go to settings, and enable a timer, the timer doesn't start. You have to close and re-launch. This (and the above crash) are because the timer is only started in `RunRefreshTimer`, which is only called in `OnLoad`, and no timer is created if the setting is 0.

**Comment by HebaruSan** [comment]
Submitted Olympic1/CKAN#3 with some fixes and one enhancement.

**Comment by Olympic1** [comment]
Merged, I will look into the Maximize issue

**Comment by HebaruSan** [comment]
The maximize thing is because `WindowState` stores `FormWindowState.Maximized` when the window is maximized, so setting it to `FormWindowState.Normal` resets it to non-maximized. So we either need to remember that we were maxmized, or use some other method to un-minimize.

Maybe we could borrow `configuration.IsWindowMaximised`?

https://github.com/KSP-CKAN/CKAN/blob/caeb50d3757633cf5b0c666799234df9a99c4608/GUI/Main.cs#L311

**Comment by HebaruSan** [comment]
Currently `configuration.IsWindowMaximised` is only set at exit. We need to set it at minimize as well for that latest fix to work.

**Comment by Olympic1** [comment]
`UpdateTrayState()`, where the fix is in, is called when the GUI is resized, minimized or maxmized.

**Comment by HebaruSan** [comment]
`UpdateTrayState` doesn't set `configuration.IsWindowMaximised`, so it'll use whatever value was loaded from disk at startup.

**Comment by Olympic1** [comment]
Tested this extensively now. When the tray icon is disabled, it uses the default behaviour as before, saving the `WindowState` when closing. When the tray icon is enabled, it saves the WindowState every time the window is resized, maximized or minimized.

**Comment by HebaruSan** [comment]
OK, I added some instrumentation to figure this out. What's happening is that IsWindowMaximised is set to true when the window is maximized, but then minimizing it sets IsWindowMaximised back to false.

Maybe you're testing with minimizeToTray set to true? I have it as false. That ought to make a difference since the assignment happens in the else block of the if statement checking `minimizeToTray && WindowState == FormWindowState.Minimized`.

**Comment by HebaruSan** [comment]
Submitted fix at Olympic1/CKAN#4.

**Comment by Olympic1** [comment]
Thought that I tried that previously, but apparantly not. Thanks

**Comment by HebaruSan** [comment]
GitHub says it can't rebase and merge, but I don't see actual conflicts.
I'm going to try pushing a rebase manually; cross your fingers.

**Comment by politas** [comment]
Well, doesn't seem to work at all on my Mate desktop.

**Comment by HebaruSan** [comment]
(I just rebooted back to Linux.)

I get a blank space in my app indicator bar in GNOME Shell (just to the left of Steam):

image

Right clicking it brings up the menu but mostly off the screen:

image

So maybe Mono doesn't like something about the image, and we might have to move the menu and fix its colors for dark themes.

@politas, if you right click where an app indicator *might* appear while the setting is enabled, can you get the menu to show up?

**Pull request merged**
