### PR TITLE
Catch ValueErrors as in KSP-CKAN/CKAN-meta#1035

### PR DESCRIPTION
**Pull request by techman83**
A small modification to 'ckan-validate.py' which is used in our testing. Gets rid of the big Traceback, we can probably do more with it.

### CODE REVIEW

**Comment by Dazpoet** [comment]
After a bit of googling I think I've gotten myself a good enough understanding of this to merge it in good conciense, also it passes travis.

**Comment by techman83** [comment]
It's a pretty safe one, really only breaks Jenkins + Indexing and easy to revert in that case.

**Comment by Dazpoet** [comment]
After looking a few more times, because who doens't love learning? I wonder if ValueError should've also been added to https://github.com/KSP-CKAN/CKAN/blob/master/bin/ckan-validate.py#L6 or have I, once again, totally misunderstood things?

**Comment by techman83** [comment]
@Dazpoet hmm, Python is something I only dabble in. To my eyes you import from to access the method/function directly. 

For example you can do this
```
import json
from jsonschema import validate

validate(json.load(ckan_file), schema)
```
versus
```
import json
import jsonschema

jsonschema.validate(json.load(ckan_file), schema)
```

I haven't fully grok'd pythons error handling, but I don't think those even need to be exported. It certainly catches ```ValueError``` without doing as such.

**Comment by Dazpoet** [comment]
Thanks for expanding on the issue, I'm doing my best to learn :)

**Pull request merged**
