### PR TITLE
changed NewUpdateDialog.zh-CN.resx

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
Because of the length of a string was toooooooo long, I have just simplified it.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@HebaruSan Have a check, tk

**Review by HebaruSan — APPROVED** [review]
Thanks, I think I recall this being discussed in #4116.

**Comment by zhouyiqing0304** [comment]
ok tk

**Comment by zhouyiqing0304** [comment]
does CKAN have Dev Channel?

**Comment by zhouyiqing0304** [comment]
I would like to take a look of the new function

**Comment by HebaruSan** [comment]
You can click the Checks tab, then the Artifacts download, to see the build with these changes.

**Pull request merged**
