### PR TITLE
Quote path to executable in URL handler .desktop file

### PR DESCRIPTION
**Pull request by reavertm**
Quote path to executable in URL handler .desktop file, likely fixes issue #1628.

### CODE REVIEW

**Comment by reavertm** [comment]
Hello? Without proper path quoting, installing .desktop file is kinda pointless :)

**Comment by politas** [comment]
This actually fails for me because the working directory is not a KSP installation (my CKAN is not stored in any of my KSP installs). Can you remove the `gui` directive? It launches fine without it. That would need some testing on Windows, I guess.

**Comment by politas** [comment]
This may fix #723, actually. Reavertm, can you check that the mimeapps.lst entry is being correctly handled, too?

**Comment by pjf** [comment]
Oh my! We absolutely need path quoting if the user's path may have spaces or other characters in it.

On my system things launch fine with the "gui" directive (on Linux), and it was there before this change, so this PR is making things objectively better than they were before, so I'm merging.

@reavertm : Thank you so much with your patience in us taking a little while to add this, and thank you so much for your contribution! this will be going out in today's release. :)

**Comment by reavertm** [comment]
Glad I could help!

**Pull request merged**
