### PR TITLE
Small text/number formatting changes to mod list

### PR DESCRIPTION
**Pull request by DasSkelett**
* Align the download count number to the right
* Align the size text to the right
* Format the download count number with thousands separators.
* Change size appendages to binary prefixes following [ISO/IEC 80000-13:2008](https://en.wikipedia.org/wiki/ISO/IEC_80000) and  [IEEE 1541-2002](https://en.wikipedia.org/wiki/IEEE_1541-2002) ;)

### CODE REVIEW

**Comment by politas** [comment]
You can bet that some people will complain about the KiB/MiB/GiB change.

**Comment by HebaruSan** [comment]
... starting with me. Is that necessary? It seems like pedantry for its own sake.

**Comment by DasSkelett** [comment]
No, not necessary. But I think more correct.
So why don't do it this way?
It's not as if this was a big effort to change.

**Comment by HebaruSan** [comment]
Basically because no one uses those abbreviations, and everyone uses MB and GB.

**Comment by DasSkelett** [comment]
So make the people use them ; )

**Comment by HebaruSan** [comment]
Well, at least 'i' is a small character. :man_shrugging:

**Pull request merged**
