### PR TITLE
Use SystemColors to source various UI colors

### LINKED ISSUE #1011: GUI colors under Linux are terrible under some themes
<a href="https://github.com/Ippo343"></img></a> **Issue by [Ippo343](https://github.com/Ippo343)**
_Saturday Dec 27, 2014 at 12:48 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/KSP-CKAN/CKAN-GUI/issues/5_

---

_From @AlexanderDzhoganov on November 20, 2014 11:44_

There seems to be something funky going on with control backgrounds on Linux i.e. the colors don't match everywhere.
Here is a screenshot to show the problem - http://i.imgur.com/CV0eEoj.png

_Copied from original issue: KSP-CKAN/CKAN#422_

### PR DESCRIPTION
**Pull request by ayan4m1**
Should fix #1011, but needs some in-the-field testing because not all of the colors are necessarily mapped well under the common dark themes.

### CODE REVIEW

**Comment by politas** [comment]
I'll give it a try.

**Comment by politas** [comment]
I don't get any change in the UI other than the window decorations

**Comment by ayan4m1** [comment]
The work in this PR shouldn't really change anything - just replaces hardcoded colors with slightly more generic stand-ins. It's ultimately up to Gtk# or Mono or something in between to choose what `ControlDarkDark` means instead of forcing a single color always.

**Comment by politas** [comment]
Yes, I tested changing my GTK theme to a dark theme. It might be a limitation of Mono Winforms, I suppose. Another Mono app I use also failed to change.

**Pull request merged**
