### PR TITLE
Create an issue template

### PR DESCRIPTION
**Pull request by plague006**
If someone wants to change something feel free, I just saw that [GitHub added this](http://venturebeat.com/2016/02/17/github-launches-templates-for-new-issues-and-pull-requests/) and after closing https://github.com/KSP-CKAN/CKAN/issues/1595 this felt cathartic.

### CODE REVIEW

**Comment by Dazpoet** [comment]
Sounds amazing to me :)

Will people just get this at the end of their issues thoguh so we will get spammar with this template forever after a merge?

**Comment by plague006** [comment]
I haven't had occasion to test it, but from the article it looks like every issue opened contains the text in the field. If we repeatedly see people not removing the text we can always just delete the template.

**Comment by Dazpoet** [comment]
Sounds good to me

**Comment by plague006** [comment]
With it merged, it is indeed real text.. shame that it's not HTML5 placeholder text.

**Comment by Dazpoet** [comment]
Better than nothing imo :+1:

**Pull request merged**
