### PR TITLE
Fixed TargetInvocationException when deselecting a mod some other mod…

### LINKED ISSUE #1371: TargetInvocationException when deselecting a mod some other mod depends on
Thanks to @plague006 for reporting this and doing the video.

Reproduction:
http://www.mediafire.com/watch/cs4fwmtfs73aoz8/untitled.mp4

Install Real Plume (either config, though stock has a significantly smaller download), select but don't install "star-trek style engines" and then unselect Real Plume -- it should give "Mod RealPlume is not in the list"

```
Unhandled exception:
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentException: Mod RealPlume is not in the list
   bei CKAN.RelationshipResolver.ReasonStringFor(Module mod) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Relationships\RelationshipResolver.cs:Zeile 518.
   bei CKAN.RelationshipResolver.get_ConflictList() in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Relationships\RelationshipResolver.cs:Zeile 482.
   bei CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KSPVersion ksp_version) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\MainModList.cs:Zeile 544.
   bei CKAN.Main.<UpdateChangeSetAndConflicts>d__86.MoveNext() in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\Main.cs:Zeile 704.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei CKAN.Main.<ModList_CellValueChanged>d__85.MoveNext() in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\Main.cs:Zeile 682.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Delegate.DynamicInvokeImpl(Object[] args)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   bei System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei CKAN.Main..ctor(String[] cmdlineArgs, GUIUser User, Boolean showConsole) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\Main.cs:Zeile 223.
   bei CKAN.GUI.Main_(String[] args, Boolean showConsole) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\Program.cs:Zeile 35.
   bei CKAN.GUI.Main(String[] args) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\Program.cs:Zeile 17.
   bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart() 
```

### PR DESCRIPTION
**Pull request by Postremus**
… depends on

Fixes #1371

### CODE REVIEW

**Comment by Postremus** [comment]
I actually have no idea, why the test failed.

**Comment by Postremus** [comment]
The test case is actually wrong. It tries to get the conflicts from the Gui's mainmodlist, but it never adds the mods to it.

**Comment by pjf** [comment]
@Postremus : Hooray! Bugs in the test suite are better than bugs in our code! :)

**Comment by ayan4m1** [comment]
The initial failure was because MainModList.Modules was empty due to improper test case setup. I am still encountering issues after that that need more attention, but I will try to fix this up and open a PR to your PR branch when I get  the test fixed.

**Comment by Postremus** [comment]
@ayan4m1 please just take over this pr, not that much time for ckan atm.

**Pull request closed without merging**
