### PR TITLE
Add downloads counter to readme

### PR DESCRIPTION
**Pull request by plague006**
It looks nice and it's good motivation.

### CODE REVIEW

**Comment by politas** [comment]
Since the graphic includes the word "downloads", maybe leave it off the text before?

**Comment by plague006** [comment]
The button is a link to the latest release.

**Comment by politas** [comment]
It doesn't look like a link, though, and it doesn't really invite clicks, to my mind. Also, I find the alignment being different to the preceding text off-putting.

**Comment by pjf** [comment]
Personally I'd have the shield (it looks cool!), and I'd have it link to the latest release (in case anyone clicks it) but leave the "Latest release" text off entirely.

**Comment by ayan4m1** [comment]
@politas Mind verifying that this is now how @pjf described it? I am in favor of the PR.

**Comment by politas** [comment]
That matches my understanding, and I think it looks neater. Merging.

**Pull request merged**
