### PR TITLE
WIP: Handle InconsistentKraken from RelationshipResolver in GUI

### LINKED ISSUE #1864: CKAN.ModuleNotFoundKraken: Cannot install <unrelated mod>, module not available
1.18.1

win 8.1 pro

i'm unable to install any mods, thrown something about exception detector being unavailable, however, there's no exception detector available to deselect. the apply changes is greyed out. 

**How to recreate this issue:** 

```
************** Exception Text **************
CKAN.ModuleNotFoundKraken: Cannot install ExceptionDetector, module not available
   at CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KspVersion ksp_version)
   at CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersion kspversion)
   at CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersion ksp_version)
   at CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

### PR DESCRIPTION
**Pull request by politas**
Finally tracked down the cause of the weirdness. Now to fix it!
Closes #1864

### CODE REVIEW

**Comment by politas** [comment]
Curently failing test/GUI/MainModList.cs/ComputeChangeSetFromModList_WithConflictingMods_ThrowsInconsistentKraken

My C# skills have failed me, and I need to work out what's happening.

**Comment by politas** [comment]
I keep getting this:

```
Test Error : Tests.GUI.MainModListTests.ComputeChangeSetFromModList_WithConflictingMods_ThrowsInconsistentKraken
   System.NullReferenceException : Object reference not set to an instance of an object
```

I don't know whether this test needs to change? If we're handling the InconsistentKraken exception, is it no longer thrown?
@ayan4m1 , can you have a look?

**Comment by politas** [comment]
The new RaiseError is throwing three error dialogs for some reason. But at least it is now throwing errors!

**Comment by ayan4m1** [comment]
@politas If you can resolve the conflicts I think this would be a good PR to merge in. What is WIP about it?

**Comment by politas** [comment]
That it isn't working properly.

**Comment by politas** [comment]
Ok, rebased, at least

**Comment by politas** [comment]
This branch is all types of messed up. I'm starting afresh.

**Pull request closed without merging**
