### PR TITLE
Remove KerbalStuff

### PR DESCRIPTION
**Pull request by Olympic1**
Remove everything KerbalStuff related out of CKAN except for the testing data.

Part of #1593

### CODE REVIEW

**Comment by politas** [comment]
Could you do a similar job for Spaceport? Ref #1621

**Comment by Olympic1** [comment]
We don't have anything spaceport related

**Comment by politas** [comment]
I'm pretty sure the Transformer is hanging around. Try that example file in #1621. Netkan goes off searching for a mod on Spaceport, then gives a weird error.

**Comment by Olympic1** [comment]
No, `JSON deserialization error` means there is an error in the JSON file (in this case a `.netkan`).

**Comment by politas** [comment]
Ah, ok. It's just that we have no specific tests for valid kref identifiers, then.

**Comment by pjf** [comment]
This looks good to me. The only thing I can think of that might cause hiccups is if a .netkan file has an explicit `kerbalstuff` URL in it, in case case I'm not sure how it will sort, but I'm not too stressed abut that.

Testing now and then merging. thank you!

**Pull request merged**
