### PR TITLE
Remove unused field

### PR DESCRIPTION
**Pull request by plague006**
From visual studio:

`Warning	1	The field 'CKAN.Main.UpdateCol' is never used	D:\CKAN\GUI\Main.Designer.cs	1455	44	CKAN-GUI`

And indeed a search for any references to it comes up empty.

### CODE REVIEW

**Comment by politas** [comment]
Oh, I'm glad someone has decided to look at this build warning message. Looking into it, now, I'm wondering whether someone created this field in order to address the other build warning: 

    Main.Designer.cs(1497,44): warning CS0108: `CKAN.Main.Update' hides inherited member 
    `System.Windows.Forms.Control.Update()'. Use the new keyword if hiding was intended

It looks to me like there may be an inherited action that's unable to be used because we're using the same identifier.

**Comment by politas** [comment]
I can't see any instance where we're attempting to call that `Update()` action. We seem to have replaced it with `UpdateModsList()`, which does little other thatn over-ride the value of the `repo_updated` parameter as it passes through to `private void _UpdateModsList(bool repo_updated)`

**Comment by politas** [comment]
Which leaves me wondering whether MainRepo.cs:98 

    UpdateModsList(repo_updated: true);

should be replaced with 

    _UpdateModsList(repo_updated: true);

in order to actually force a complete update of the mods list after someone clicks the "Refresh" toolbar button.

**Comment by politas** [comment]
Chasing the rabbot down the hole, I find that the `System.Windows.Forms.Control.Update()` method (I've used the term "action" instead of "method" above, incorrectly)	
"Causes the control to redraw the invalidated regions within its client area."

So this could be what is causing the graphical problems on MacOSX (#1673)

**Comment by plague006** [comment]
Closing in favour of a PR @politas will open to more completely address the source of this issue.

**Pull request closed without merging**
