### PR TITLE
Replace deprecated mozroots command with cert-sync for Travis

### LINKED ISSUE #1787: mozroots - Couldn't retrieve the file using the supplied information.
**CKAN Version:** 
latest
**Operating System:** 
ubuntu
**The issue you are experiencing:** 
```
$ mozroots --import --ask-remove 
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Couldn't retrieve the file using the supplied information.
```

### PR DESCRIPTION
**Pull request by politas**
Explicitly adds ca-certificate-mono package, in case it doesn't get included with mono-complete
@techman83, can you check this?
Closes #1787

### CODE REVIEW

**Comment by techman83** [comment]
If we're altering apt sources we should convert to the new method so that we can use the Travis container infrastructure instead of VMs.

Here's a yaml example of how to add a ppa + packages:

```
addons:
  apt:
    sources:
    - git-core
    packages:
    - git
    - aspell
```

**Comment by ayan4m1** [comment]
Also, `ca-certificates-mono` is not in the [package whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) that Travis filters on.

**Comment by politas** [comment]
Yeah, I think it's pretty clear that I don't know what I'm doing with Travis.

**Comment by politas** [comment]
Closing in favour of #1879

**Pull request closed without merging**
