### PR TITLE
Added include_only and include_only_regexp

### LINKED ISSUE #228: Add `include_only` and `include_only_regexp`
From 17405ea:

The CKAN filters (does not install) any file which _matches_ the regexp. The negative look-arounds means we can have a regexp which matches everything _except_ for a given file or path. Yes, that's needlessly complex.

To be honest, in addition to the filter fields, we should probably have their inverse as well, which I propose as `include_only` and `include_only_regexp`. It would be an error to have both filters and include_onlys in the same stanza.

That means we can have `"filter" : "config.cfg"` in the main document, and `"install_only" : "config.cfg"` in the configuration documents, which makes things much easier and more obviously correct.

### PR DESCRIPTION
**Pull request by Zane6888**
This PR adds two fields which practically work as negative filter/filter_regexp. 
Also Includes a test and changes to the CKAN.schema to make sure there are only filter or include_only fields but never both. 

I hope I didn't miss anything, don't really know the code-base yet.

Closes #228

### CODE REVIEW

**Comment by plague006** [comment]
I'm confused on the use-case for this since `find` and `find_regexp` only match to a single file or folder.

**Comment by Dazpoet** [comment]
This requires a rebase now after #1578 was merged it seems.

**Comment by ayan4m1** [comment]
LGTM, @politas can you give some insight on what direction the project should be taking w/r/t this schema change?

**Comment by politas** [comment]
I think it's a great idea. It would make some mods much easier to configure installs for. To implement, we'd need to make the next release 1.23.0, and have this feature require spec_version v1.23

**Pull request closed without merging**
