### PR TITLE
Add identifier to metadata panel

### PR DESCRIPTION
**Pull request by plague006**
Recreation of #1470 without Visual Studio designer's extra code because I'm interested to see how travis reacts.

### CODE REVIEW

**Comment by plague006** [comment]
@Postremus I'm really unclear on which changes Designer is making that Jenkins doesn't like, but when I add the relevant code/make the changes manually it passes (I had this same experience in the past when working with the GUI).

**Comment by Postremus** [comment]
@plague006 
The failed test has nothing to do with the Designer's changes. A 403 was thrown when testing the AutoUpdater:
```
Errors and Failures:
1) Test Failure : Tests.Core.AutoUpdate.AutoUpdate.FetchCkanUrl
     Expected: <CKAN.Kraken>
  But was:  <System.Net.WebException> (The remote server returned an error: (403) Forbidden.)
  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0 
at Tests.Core.AutoUpdate.AutoUpdate.FetchCkanUrl () [0x00000] in <filename unknown>:0
```

However, since your PR is cleaner, we will go with yours.

**Comment by plague006** [comment]
Ah, just an odd coincidence.

**Comment by Postremus** [comment]
Tested, works. Merging with my thanks!

**Pull request merged**
