### PR TITLE
New Translation of NewUpdateDialog.zh-CN.resx

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
为什么有人会把一些梗放在这里？？？
我有点点生气，这是管理工具，不是玩梗场所啊

Translation from ChatGPT:
Why do some people put memes here??? I'm a bit annoyed; this is a management tool, not a place for jokes.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@HebaruSan What happened? Why someone is playing memes?

**Comment by zhouyiqing0304** [comment]
@HebaruSan Remember to compile

**Comment by zhouyiqing0304** [comment]
I'm really love this program.
Keep 努力
I believe it will be better soon

**Comment by HebaruSan** [comment]
Hi @zhouyiqing0304, thanks for another contribution!

> Why do some people put memes here??? I'm a bit annoyed; this is a management tool, not a place for jokes.
> What happened? Why someone is playing memes?

Can you explain what you mean by this? What memes? I noticed one of these strings means "Next time for sure" according to Google Translate (I don't have a ChatGPT account, sorry). Is that what you're referring to?

That string was contributed by @050644zf in #3014, so you would have to ask them why it was chosen. The members of the CKAN dev team do not speak Chinese, so we have to rely on contributors who do speak it to make good choices, with some sanity checking with translation tools.

**Review by HebaruSan — APPROVED** [review]
Thanks again!

**Comment by 050644zf** [comment]
Hi @HebaruSan & @zhouyiqing0304 

It's true that "下次一定" is a popular meme b4. And I used it here for the following reason.

First, in meaning. The original en string of `CancelUpdateButton.Text` is `Not Now`, which contain the meanings of "Reject the update this time" and "inform me next time".

Meanwhile the string in button are limited by button size so keep the string length as close as en is necessary or i have to ask devs to tweak them. 

So restricted by both meaning and length, i think "下次一定" is a good choice, it's a neutral word which means "Next time for sure". And understanding it need no prerequisite, this word is frequently used in many place until it became a meme.

As for this pr, i found the contributor adding some unnecessary string after the translation like adding `(Recommend)` after `Download` in line 124 and adding `(You can update later in Setting > CKAN Setting > Check update)` after `Not Now`. The additional length of string will definitely overflow the button. Please take a note on it.

Regards.

**Comment by zhouyiqing0304** [comment]
> 嗨&
> 
> 的确，“下次一定”是一个流行的模因 b4。我在这里使用它的原因如下。
> 
> 首先，在含义上。的原始 en 字符串 是 ，其中包含“这次拒绝更新”和“下次通知我”的含义。`CancelUpdateButton.Text``Not Now`
> 
> 同时，按钮中的字符串受按钮大小的限制，因此请保持字符串长度尽可能接近 en，否则我必须要求开发人员调整它们。
> 
> 因此，受含义和长度的限制，我认为“下次一定”是一个不错的选择，它是一个中性词，意思是“下次肯定”。理解它不需要先决条件，这个词在很多地方经常使用，直到它成为一个模因。
> 
> 至于这个 pr，我发现贡献者在翻译后添加了一些不必要的字符串，例如在第 124 行添加之后并在 .额外的字符串长度肯定会溢出按钮。请记下它。`(Recommend)``Download``(You can update later in Setting > CKAN Setting > Check update)``Not Now`
> 
> 问候。

emmmm, You are right I think...

**Comment by zhouyiqing0304** [comment]
> 嗨，感谢您的再次贡献！
> 
> > 为什么有些人把表情包放在这里???我有点生气;这是一个管理工具，而不是一个开玩笑的地方。 发生了什么事？为什么有人在玩模因？
> 
> 你能解释一下你的意思吗？什么模因？我注意到其中一个字符串的意思是根据谷歌翻译的“下次肯定”（我没有 ChatGPT 帐户，对不起）。这就是你所指的吗？
> 
> 该字符串是由 #3014 贡献的，因此您必须询问他们为什么选择它。CKAN开发团队的成员不会说中文，因此我们必须依靠会说中文的贡献者来做出正确的选择，并使用翻译工具进行一些健全性检查。

then chatgpt don't always need an account.
You can use it in https://chatgpt.com/ or https://openai.com/chatgpt/

**Pull request merged**
