### PR TITLE
Create text UI inspired by Turbo Vision

### PR DESCRIPTION
**Pull request by HebaruSan**
# CKAN Console UI

There has been discussion lately of replacing CKAN's current WinForms GUI with a GTK# one (#1840), as well as of enhancing the CmdLine interface (#2161, #2174). While this pull request doesn't do either of those things, I think it's related and may satisfy some of the needs that inspired those requests.

This pull request adds a new cross-platform UI modeled after the pre-Windows text interfaces of the late 1980s and early 1990s such as Borland's Turbo Vision and IBM's Common User Access, influenced by the Debian package management application "aptitude", with a few modern tweaks. I hope it can provide value in the niche between a full-on GUI and somewhat cumbersome command line tools.

## Status: **Open for more feedback, but probably ready to merge**

I think this project is pretty complete; I've addressed all bugs that I was able to find and added all the reasonable features I could think of. However, my knowledge of CKAN is not as deep or thorough as others', so there's a good chance I missed something. Please help me find:

- Unhandled exceptions/crashes and other bugs
- Missing features
- Better names for anything and everything
- Colors that are hard to read
- Bad layout
- How to make useful tests
- ~~Whether the key bindings work on MacOS X~~
- Etc.

I developed this on Linux and also tested in a Windows VM.
I do not have a Mac available for testing.

## New-ish features

- Import downloads option (related to #1788)
- After registry update, Y/N prompt to show newly compatible mods if any (related to #1766 and #1923)
- Search of `~dkeyword` shows reverse dependencies (related to #1100, #1494, and KSP-CKAN/NetKAN#5646)
- Instead of a forced registry auto-update, shows the approximate time since last update so user can press ctrl-R if needed (related to #2099)
- Shows where a download is hosted on the mod info screen (related to #2062)
- Shows when a mod was installed on the mod info screen (related to #954 and #1933)
- Can view the mod info screen for optional dependencies (related to #858 and #1868)
- Audit recommendations option to browse optional dependencies of already installed mods (related to #1764)
- Text search looks at identifier, name, and abstract (related to #1313)

## Dependencies

There are no third party dependencies; the whole thing is built directly on top of `Console.BackgroundColor`, `Console.SetCursorPosition`, etc., using classes contained in the `CKAN\ConsoleUI\Toolkit` folder (all written by me and kosher to release under CKAN's license). This has several advantages:

- No risk that a library we depend on will disappear or cease to be supported
- No risk of being affected by bugs we can't fix in a third party package
- We can safely extend the toolkit with more UI elements and refactor whatever we like as needed
- Strong cross-platform support, since it can run anywhere .NET and Mono can

## Screenshots

When you run `ckan consoleui`, a futuristic splash/loading screen appears:

image

image

If you have a default game instance, the next screen is the list of mods:

image

In modern style, the top right corner features a search box:

image

... which can also search by `@author`:

image

... as well as a dropdown "hamburger" menu for less commonly accessed functions:

image

... including sorting the list:

image

After you update the registry, it alerts you to any newly added mods, since that's a common request on the forum thread:

image

image

A help screen summarizes the key bindings and special search formats:

image

You can press enter on the mod list screen to view detailed information about a mod, including relationships, versions, and the text description:

image

Pressing Ctrl+D on that screen jumps you to an abbreviated version of the install screen to download the mod:

image

Another screen allows the user to work with game instances; this is the first screen if you have no default instance:

image

(This was how I found the issue fixed by #2175.)

image

The user can create and edit game instances on this screen:

image

Once you've selected some mods to install, F9 takes you to the installation screen, which first prompts you to select any needed dependencies:

image

image

Then confirms the installation:

image

(This was why I wanted to simplify `IUser` in #2163.)

Then performs the downloads and installs:

image

### CODE REVIEW

**Comment by dbent** [comment]
I think I'm in love.

**Comment by HebaruSan** [comment]
#rebuild

**Comment by politas** [comment]
This is awesome! I especially love the splash screen! I'd say it reminds me of things "back in the day", but it also strongly reminds me of the Midnight Commander, which I use every day.

**Comment by politas** [comment]
@KSP-CKAN/macos-testers, any chance y'all can give this a try?

**Comment by HebaruSan** [comment]
> @KSP-CKAN/macos-testers, any chance y'all can give this a try?

That group has only one member other than you; maybe I can recruit people who submitted Mac-related issues... @Maxzhao1999, would you be available to report bugs on a Mac? I can provide a compiled EXE for testing, just let me know.

I started another branch locally to add support for the current head of #1888. Hopefully git won't make it too difficult to keep it up to date with both projects.

**Comment by HebaruSan** [comment]
Attempting to rope in some more admitted Mac users from #760 and #1334: @bax-, @alampros, @savagerose, @Heliosmaster, @desplesda, @mgsdk, @RichardLake, @Crazor, @CalMlynarczyk

Would any of you be willing to take the changes from this PR for a test drive on your Mac? Compiled EXE available upon request.

**Comment by Maxzhao1999** [comment]
I’d love to help! Just tell me what you want me to do and I’ll try it out this weekend.

**Comment by HebaruSan** [comment]
@Maxzhao1999 , that's fantastic, thank you!!

- [ckan-consoleui.zip](https://github.com/KSP-CKAN/CKAN/files/1459569/ckan-consoleui.zip)

If you unzip that file, there should be a `ckan.exe` inside. Try this:

1. Open a Terminal
2. `cd` to the directory where you unzipped the file
3. Run `mono ckan.exe consoleui`

That should get you into the new screens. To the best of my knowledge, no one has run this on OSX _at all_ yet, so for all I know it may not even run, or it may be completely unusable. I'm interested to know about any problems that you find in trying typical use cases, but especially cases where it works differently than it does on Windows or Linux.

- View the list of mods and scroll through it
- View info about a mod and download it
- Install a mod
- Uninstall a mod
- Quit the program
- Etc.

I am mostly concerned about the key bindings, since I had to make platform-specific adjustments to get them working the same way on Linux and Windows. Keep an eye on the bottom bar where key bindings are listed, and check the F10 menu and the Alt+H help screen to see a few more key bindings. If any of them don't seem to function, then I might have to create an additional testing EXE to capture the key values that are being sent. But I'd like to hold off on doing that until it's necessary.

Thanks again!

**Comment by Maxzhao1999** [comment]
Thanks for the detailed response, I’ll go through them and give you feedback hopefully in the next few days. Glad to be of help!

**Comment by Maxzhao1999** [comment]
Hey, I've had a quick look at the program and here are some feedbacks.

- The program runs in macOS.

- No problem scrolling through the mods

- No problem viewing info for mods

- Search works well, the shortcuts such as @Author works fine too

- No problem quitting the program, F10 works fine

Some problems include:

- Cannot install or uninstall mods, Alt-A, +sign and Alt-D does not work

- Help screen can be opened by F1 but not Alt-H

Also, I'd just like to say that although I've not been able to install or uninstall any mods, the consoleui seems to be much smoother than the current GUI and it looks amazing!

I'd love to help further!

**Comment by HebaruSan** [comment]
Thanks, that's exactly the kind of feedback I was looking for! :+1: 

It sounds like the Alt keys are a problem, which in retrospect is not surprising, so I've reassigned them:

| Function | Previous key | New key |
| --- | --- | --- |
| Quit | Alt+X | Ctrl+Q (Alt+X still silently supported on Windows and Linux) |
| Save instance | Alt+A | F2 (the save key from Turbo C++) |
| Apply changes | Alt+A | F9 (the build key from Turbo C++) |
| Update registry | Alt+U | F5, Ctrl+R (browser refresh keys) |
| Download mod | Alt+D | Ctrl+D |
| Help | Alt+H | (hidden on Mac since F1 works) |

The plus key is going to be more complicated; we'll need to capture info about the key so I know how to fix it. Since I've had to do this previously for other issues, I decided to add it as a menu option.

New download:
- [ckan-consoleui.zip](https://github.com/KSP-CKAN/CKAN/files/1462461/ckan-consoleui.zip)

Please download and unzip that new version, start it with `mono ckan.exe consoleui --debug` (the **--debug** part is new), and find this option in the menu:

image

When it prompts you to press a key, press your plus key, and it should report details about it. Please let me know what it says!

**Comment by Maxzhao1999** [comment]
Below is what it says:
Key:                0
KeyChar:        0x3d
Modifiers:      0

Also, the new keys above works! Yay!

**Comment by HebaruSan** [comment]
Thanks for testing!
Those values seem to correspond to pressing the '=' equals key without shift; or at least that's what it says for me when I do that.
What happens if you capture the key while holding down shift?

**Comment by Maxzhao1999** [comment]
Aha, sorry about that, silly mistake.  Here’s the correct one:
Key: Add
KeyChar: 0x2b
Modifiers: 0

**Comment by HebaruSan** [comment]
Hmm, that should be what it's already using. Are you sure that you were pressing shift before when trying to install mods? Maybe that key isn't clear enough...

**Comment by pjf** [comment]
This... this is *beautiful*. *Thank you*.

**Comment by Maxzhao1999** [comment]
That might just be the problem, me being silly XD

**Comment by Maxzhao1999** [comment]
I’ll check if everything is working again tmr morning and will add a new version of Mac CKAN just for this UI on top of the old one if so.

**Comment by HebaruSan** [comment]
Finally looked into what "repositories" refers to (I had not used that feature before). They're now listed on the screen for editing an instance (I called them "Mod List Sources" instead of "repositories" because it's ambiguous, CKAN-meta is a repository, NetKAN is a repository, etc.):

image

The screen for adding/editing a repo allows free editing with basic validation and has the built-in default repos listed in its main menu:

image

**Comment by politas** [comment]
NetKAN is not a repository. NetKAN is metametadata to automate repository updates.

**Comment by HebaruSan** [comment]
I know it's not a "repository" in the sense that Repository.cs means it, but it _is_ in this sense:

image

We also have the `resources.repository` metadata for pointing to a mod's GitHub page. I just wanted something that would answer the question, repository _of what?_

**Comment by dbent** [comment]
[Software repository](https://en.wikipedia.org/wiki/Software_repository) is a pretty prolific term of art and what most other package managers refer to the concept as. People that need to be aware of the distinction between a *software* repository and a *source* repository are pretty much limited to developers and it's pretty trivial to explain it to them.

Unfortunately I won't have time for a a full code review until the end of the week.

**Comment by HebaruSan** [comment]
(The latest CI error seems to be a [problem with Travis](https://www.traviscistatus.com/incidents/rg2rb5mm71vl), not this PR.)

**Comment by HebaruSan** [comment]
Has anyone had a chance to take this project for a test drive? I've been continuing to make tweaks and small fixes, but I think it's pretty solid at this point, so I'm ready to focus on your bug reports.

If nobody has time, what about merging it to get feedback from users after the next release? Since it's a separate command line argument, no one should be affected accidentally. I could post a short reply to the forum thread explaining how to access it, with caveats about it being in a beta state, and hopefully enough people would be interested that we'd get decent coverage of the possible use cases.

(It would be _really_ nice to have this ready in time for #2187, since the run script could default to this UI on Linux when the GUI can't be launched, i.e. if $DISPLAY is empty. Also, I have a local branch with ConsoleUI support for #1888, but it's hard to keep it in sync with two separate in-progress projects.)

**Comment by politas** [comment]
I'll have a look now. It sounds pretty ready to go.

**Comment by politas** [comment]
I note you haven't implemented a KSP Compatibility dialog. Any particular reason? That's a very popular feature

**Comment by politas** [comment]
Ooh, I like the Import Downloads feature. We'll have to pull that into the GUI as well!

**Comment by politas** [comment]
Exiting after loading an instance but not doing anything produces an unhandled Exception:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Stream has been closed'.
  at System.IO.FileStream.Flush () [0x0000d] in <62f5937022004555807e6c57c33f6684>:0 
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00094] in <62f5937022004555807e6c57c33f6684>:0 
  at System.IO.StreamWriter.Dispose (System.Boolean disposing) [0x00022] in <62f5937022004555807e6c57c33f6684>:0 
  at System.IO.TextWriter.Dispose () [0x00000] in <62f5937022004555807e6c57c33f6684>:0 
  at (wrapper remoting-invoke-with-check) System.IO.TextWriter:Dispose ()
  at CKAN.RegistryManager.ReleaseLock () [0x00008] in <79dc945121f74037acfea575c1b164da>:0 
  at CKAN.RegistryManager.Dispose (System.Boolean safeToAlsoFreeManagedObjects) [0x00000] in <79dc945121f74037acfea575c1b164da>:0 
  at CKAN.RegistryManager.Finalize () [0x00000] in <79dc945121f74037acfea575c1b164da>:0 
```

**Comment by politas** [comment]
The "Continue Y/N?" dialog covers some details of what is to be installed, and if the list is too long for the screen, there's no way to scroll.

**Comment by HebaruSan** [comment]
Thanks! That's a good batch to get me started. Short replies:

- Compatibility dialog - I don't use it, so I just missed the feature. I'll look into it.
- Import Downloads - Yeah hopefully! I tried to abstract out the core of it as a generic algorithm via IUser, so please let me know if there's a good place to put that in Core.
- System.ObjectDisposedException - I would greatly appreciate any tips that anyone can share on this one. I did see that periodically during development, but I thought I had resolved it, and I'm not sure what would cause it to begin with.
- Install screen covered by popup - Good point, I'll see what I can do.
- Install screen scrolling - If I have to. :)
- Install screen clearing - Agreed, and honestly I don't understand how it's keeping the previous text. It should be making a new instance of that screen every time. Maybe something to do with delegates and continuations...?
- Redundant recommendation screens - Thanks for the test case, will investigate

**Comment by HebaruSan** [comment]
Pushed some fixes; see edit of previous reply for what's done and what's pending.

Compatible version stuff:

image

The add popup loads the same list that GUI uses, or you can type in the box at the bottom:

image

The popup doesn't let you accept the text box if it's invalid:

image

But a valid version is OK:

image

**Comment by ProfFan** [comment]
@HebaruSan I am willing to test drive this :) Can you provide a binary file?

**Comment by HebaruSan** [comment]
@ProfFan, sure thing! :+1: 

- [ckan-consoleui.zip](https://github.com/KSP-CKAN/CKAN/files/1512843/ckan-consoleui.zip)

Thanks for offering to help!

**Comment by ProfFan** [comment]
@HebaruSan Works fine for me! However there is a exception when exit:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Stream has been closed'.
  at System.IO.FileStream.Flush () [0x0000d] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x00094] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.IO.StreamWriter.Dispose (System.Boolean disposing) [0x00022] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at System.IO.TextWriter.Dispose () [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
  at (wrapper remoting-invoke-with-check) System.IO.TextWriter:Dispose ()
  at CKAN.RegistryManager.ReleaseLock () [0x0000d] in <f58a67bc99f44136bacf55d711995866>:0
  at CKAN.RegistryManager.Dispose (System.Boolean safeToAlsoFreeManagedObjects) [0x00001] in <f58a67bc99f44136bacf55d711995866>:0
  at CKAN.RegistryManager.Finalize () [0x00001] in <f58a67bc99f44136bacf55d711995866>:0
```

**Comment by HebaruSan** [comment]
Thanks! I think I finally got to the bottom of that exception. The download link is updated with the latest fixes.

**Comment by HebaruSan** [comment]
One thing was missing:

image

**Comment by HebaruSan** [comment]
Latest commit should address @politas's remaining comments. It was a challenge to fit the popup and the messages on screen at the same time and also allow scrolling the messages from within the popup, but this is what I came up with:

install-animated

**Comment by HebaruSan** [comment]
Added a `--debug` menu option in the mod info screen to show the full metadata:

image

**Comment by DyBev** [comment]
Is there a way for us to use the import from a .ckan file or is this something not supported / missing feature? I can't seem to find anything about it.

**Comment by HebaruSan** [comment]
I think that's not currently in the ConsoleUI, but you can use the command line tools to do it:

```
mono /path/to/ckan.exe install -c myfilename.ckan
```

**Comment by Jamestcoe** [comment]
Untitled Image
(that path is copy from the folder opened with the steam browse game folder function)
So any one knows the correct way to add a game instance with this ui.
I am using a iMac with a i5 cpu and the os being Sequoia 15.7.4
Screenshot 2026-03-09 at 3 41 10 PM
(and this path is copy directly from the Finder)
(I think I might need to delete all of the stuff before the /Applications for it to work)tried that and it did't work.

**Comment by Jamestcoe** [comment]
and no, removing the .app also don't work

**Comment by HebaruSan** [comment]
@Jamestcoe, it just needs the folder containing the .app bundle, not the .app bundle itself.

**Comment by Jamestcoe** [comment]
Ok so where should the CKAN program be placed at in relation to KSP it self.

**Comment by HebaruSan** [comment]
Doesn't matter, anywhere is fine.

**Comment by Jamestcoe** [comment]
it seem to be a zsh: permission denied error, so not a issue with CKAN in any ways

**Pull request merged**
