### PR TITLE
Switch from outdated SharpZipLib.Patched to newer SharpZipLib

### PR DESCRIPTION
**Pull request by DasSkelett**
## Motivation
https://github.com/KSP-CKAN/NetKAN/issues/8425 and https://github.com/KSP-CKAN/NetKAN/issues/8315 show some weird errors when trying to extract certain zips with special characters on Windows systems with CJK locales.
_Maybe_ this is a bug of `SharpZipLib`, and _maybe_ it is already fixed in a newer versions. It's a total stab in the dark, but worth a try. I've asked affected users to try a debug build with an updated version of the package, we should know when we get an answer.

In any case, there have been some improvements to that library in the releases since, the usual performance enhancements, and support for BZip2 compression.

We have been using a "Patched" version of this library, which has been deprecated now. Its [NuGet page](https://www.nuget.org/packages/ICSharpCode.SharpZipLib.Patched) doesn't give any details on what it's patching, but it seems to be related to:
* https://github.com/KSP-CKAN/CKAN/issues/221
* https://github.com/KSP-CKAN/CKAN/pull/222
* https://github.com/pjf/SharpZipLib/commit/8ec3e47283b2c201474f731a52b8c752c5127e2e
The fix is applied upstream since v1.0.0-rc1:
* https://github.com/icsharpcode/SharpZipLib/pull/53

## Changes
Switch to the upstream SharpZipLib, v1.3.1. I haven't seen any breaking changes, and mod installation and inflation still works perfectly fine in my testing.

Add `venv/` folders to `.gitignore` - I have one inside `bin/` for the Python scripts there.

Add `exitstatus` to `bin/requirements.txt`. For some reason I didn't catch the missing dependency during the PRs for the `ckan-merge-pr.py`.

(Gonna give this the "Enhancement" flair for the time being and not say it closes the issue https://github.com/KSP-CKAN/NetKAN/issues/8425, since we don't know for sure yet)

### CODE REVIEW

**Comment by HebaruSan** [comment]
> image

Except that _will_ auto-close; all it takes is linking to the issue after the word "closes" or "fixes":

image

**Comment by DasSkelett** [comment]
Ugh, I've paid attention that it doesn't underline it in the PR preview, but apparently it only happens once the PR is created. Let's do some trickery.

**Review by HebaruSan — APPROVED** [review]
:game_die:

**Comment by HebaruSan** [comment]
Hmm, this might have caused a new problem:

image

That mod hasn't updated since August, and it doesn't contain any duplicates:

image

Is this version of the lib _less_ able to handle CJK locales?

**Comment by DasSkelett** [comment]
Interestingly this inflates and installs successfully for me, even though I had problems with UTF-8 in #3323 :confused:

**Comment by HebaruSan** [comment]
> Interestingly this inflates and installs successfully for me

Me, too. Maybe the Inflator's instance is missing some locale data?

**Comment by DasSkelett** [comment]
Now this is interesting. Running `mono netkan.exe Wanhu-Common.netkan` inside a `mono:latest` container:
```
root@3f119569761c:/ckan/_build# mono netkan.exe --version
v1.30.1+bf7064fbd8fa

root@3f119569761c:/ckan/_build# mono netkan.exe Wanhu-Common.netkan
5855 [1] FATAL CKAN.NetKAN.Program (null) - https://spacedock.info/mod/2507/LongMarch-10?CZ-10?/download/1.3 is not a valid ZIP file:
Error instep EntryHeader for Wanhu/Wanhu_Parts/Flags/Flag??????.png: Exception during test - 'Name is invalid'
```

I expected to see the "multiple files" error, but instead got the on from https://github.com/KSP-CKAN/NetKAN/issues/8425, but on Linux :exploding_head:

**Comment by techman83** [comment]
Good chance the container is missing some locale data. I doubt it's included.

**Comment by DasSkelett** [comment]
Looks like SharpZipLib changed the default for reading and writing zips _away_ from UTF-8 in version 1.1.0:
https://github.com/icsharpcode/SharpZipLib/issues/591

Setting `ICSharpCode.SharpZipLib.Zip.ZipStrings.UseUnicode = true;` right at the beginning in `Program.cs` solves the above exception and makes `netkan.exe` work in a completely fresh Mono container again :tada:

**Comment by HebaruSan** [comment]
> Setting `ICSharpCode.SharpZipLib.Zip.ZipStrings.UseUnicode = true;` right at the beginning

Is there a non-static equivalent? That's a big ugly in terms of encapsulation.

**Comment by DasSkelett** [comment]
There seems to be an overhaul of this in progress, which also mentions going back to support Unicode by default (for creating new zips judging from the discussion, not sure if and how this would affect reading zips):
https://github.com/icsharpcode/SharpZipLib/pull/592

Otherwise I haven't really digged into it yet, I'm currently trying to write a unit test for this in order to prevent this in the future, and also simpler patch testing.

**Comment by HebaruSan** [comment]
It looks like the SharpZipLib team is moving in a good direction, but it's less clear when those changes will land. I'm comfortable setting the static bool as a short term workaround, and I've subscribed to their repo's release notifications so we can revisit this.

**Pull request merged**
