### PR TITLE
[WIP] Change font away from `Microsoft Sans Serif`

### LINKED ISSUE #1284: FontFamilyNotFound error on OSX 10.6.8
Trying to start up CKAN with a simple `mono ckan.exe` on OSX 10.6.8 results in:

```
exception inside UnhandledException handler: Object reference not set to an instance of an object

[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]
  at System.Drawing.GDIPlus.CheckStatus (Status status) [0x00000] in <filename unknown>:0
  at System.Drawing.Font.GetHeight (Single dpi) [0x00000] in <filename unknown>:0
  at System.Drawing.Font.GetHeight () [0x00000] in <filename unknown>:0
  at System.Drawing.Font.get_Height () [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Drawing.Font:get_Height ()
  at System.Windows.Forms.XplatUICarbon.GetAutoScaleSize (System.Drawing.Font font) [0x00000] in <filename unknown>:0
  at System.Windows.Forms.XplatUI.GetAutoScaleSize (System.Drawing.Font font) [0x00000] in <filename unknown>:0
  at System.Windows.Forms.Form.GetAutoScaleSize (System.Drawing.Font font) [0x00000] in <filename unknown>:0
  at System.Windows.Forms.Form..ctor () [0x00000] in <filename unknown>:0
  at CKAN.Main..ctor (System.String[] cmdlineArgs, CKAN.GUIUser User, Boolean showConsole) [0x00000] in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) CKAN.Main:.ctor (string[],CKAN.GUIUser,bool)
  at CKAN.GUI.Main_ (System.String[] args, Boolean showConsole) [0x00000] in <filename unknown>:0
  at CKAN.CmdLine.MainClass.Gui (CKAN.CmdLine.GuiOptions options, System.String[] args) [0x00000] in <filename unknown>:0
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0
```
Looks like whatever font is trying to be used for the GUI doesn't exist? What font are you trying to reference? The non-GUI commands work just fine, though.

### PR DESCRIPTION
**Pull request by plague006**
TIL MS Sans Serif not only isn't free, but is rather expensive (for what it is): http://www.fonts.com/font/microsoft-corporation/microsoft-sans-serif

This may potentially resolve #1284, unable to test personally (no access to MacOS).

http://imgur.com/a/um0id
Old on right, new on left

### CODE REVIEW

**Comment by plague006** [comment]
This change fails to resolve #1284, closing this PR to let someone else take over the reins.

**Comment by plague006** [comment]
Thanks to @Postremus for showing me the way. Form font changed to Tahoma.

**Comment by pjf** [comment]
Does the Windows Forms library allow us to provide a list of font choices (similar to CSS)? Provided a font has the same metrics (character proportions) as what we've been using, I doubt we'd be too stressed about which one is used. (For example, Helvetica, Arial, FreeSans and Nimbus Sans all have identical metrics, and so can be used interchangeably.)

Reason I'm asking is that Linux systems may not have the MS fonts installed at all, and older OSX versions won't have Tahoma by default.

**Comment by plague006** [comment]
I had completely forgotten this PR. The change didn't fix #1284 and aside from that issue I haven't seen any complaints about font. So I'm closing this under the "if it ain't broke don't fix it" doctrine (and also a font change causes issues in formatting).

**Pull request closed without merging**
