### PR TITLE
Handle more meta changes

### PR DESCRIPTION
**Pull request by ayan4m1**
Rebased #1730 against master in case it is useful, feel free to close otherwise.

### CODE REVIEW

**Comment by politas** [comment]
#1730 is a public branch, so could you PR to that branch instead of to master?

**Comment by ayan4m1** [comment]
Nah, I had to rebase and the history is different. I could unpush and repush the branch entirely, but I didn't want to overwrite someone's work like that. Ultimately I'm happy to do it, just need some guidance on what to do.

**Comment by politas** [comment]
People use a public branch specifically in order to enable a more collaborative method of working on a change, so don't think of it as "overwriting someone's work", but rather as "contributing to their work", just as we're all contributing to the CKAN on the larger scale.

**Comment by ayan4m1** [comment]
Got it, closing this out.

**Comment by politas** [comment]
Merged

**Pull request closed without merging**
