### PR TITLE
Fix home/end, url handler, typing nav, and dependency double click

### PR DESCRIPTION
**Pull request by HebaruSan**
## Problem

If you do any of the following:

- Press Home on the mod list
- Press End on the mod list
- Invoke the URL handler
- Start typing a mod name on the mod list
- Double click a mod in the mod info dependency tree

... this exception occurs:

```
System.InvalidOperationException: Die aktuelle Zelle kann nicht auf eine unsichtbare Zelle festgelegt werden. (Rough translation: the current cell can't be set to an invisible cell)
   bei System.Windows.Forms.DataGridView.set_CurrentCell(DataGridViewCell value)
   bei CKAN.Main.ModList_KeyDown(Object sender, KeyEventArgs e)
   bei System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   bei System.Windows.Forms.DataGridView.OnKeyDown(KeyEventArgs e)
   bei System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   bei System.Windows.Forms.DataGridView.ProcessKeyEventArgs(Message& m)
   bei System.Windows.Forms.Control.WmKeyChar(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Cause

These all work by setting `ModList.CurrentCell` to a row's third cell, for reasons explained here:

https://github.com/KSP-CKAN/CKAN/blob/3bc537637e8f4452c9787699045d61b4d869061f/GUI/Main.cs#L1055-L1056

However, as of #2671, the third cell is Replace instead of Name, and as of #2690, it's hidden most of the time. A hidden cell cannot be the current cell, so an exception is thrown. This is essentially the same problem as #2703, but it's not specific to the mark-all-updates operation.

## Changes

Now we look for usable columns in this order:

1. The current column, if any, to avoid scrolling horizontally
2. The first visible non-checkbox column, if any
3. The Installed checkbox column (always visible fallback)

In addition, the fix for #2704 is modified to use this same logic. I think the original reasoning from the comment quoted above applies here, and so we should avoid setting focus to checkboxes when we can.

Fixes KSP-CKAN/NetKAN#7108.

### CODE REVIEW

**Comment by DasSkelett** [comment]
Why does it show my name for the label remove (and in other occasions)?
Is this because I am the last one who logged in on the Waffel page?

**Comment by HebaruSan** [comment]
Yeah, that Waffle thing likes to make automatic changes for reasons I don't understand. It did it in my name for a while when I first joined as well.

**Comment by HebaruSan** [comment]
Welcome to the team by the way, @DasSkelett! I'm excited about having a more... active... collaborator. :)

**Comment by DasSkelett** [comment]
Thanks. You tell me something, that was quite a hot start with you going on vacation, and @politas releasing a new major version, and all that exactly in those two weeks where I had training every two days for a fire brigade performance test....

**Pull request merged**
