### PR TITLE
Remove non-functioning code on available command

### LINKED ISSUE #359: CmdLine: Handle console-less operations (including cygwin mintty terminal)
ckan.exe is able to complete some operations when running in a cygwin bash/mintty session, but not all.

`./ckan.exe available` crashes with the following output

```
$ ./ckan.exe available
Mods available for KSP 0.25.0


Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at CKAN.CmdLine.MainClass.Available()
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

`./ckan.exe install` attempts installation but immediately crashes when polling for user input:

```
$ ./ckan.exe install RemoteTech
About to install...

 * RemoteTech v1.5.1

Continue? [Y/N]

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at CKAN.User.YesNoDialogConsole(String text)
   at CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOptions options)
   at CKAN.CmdLine.MainClass.Install(InstallOptions options)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

`./ckan.exe remove` behaves identically to `ckan.exe install`:

```
$ ./ckan.exe remove RemoteTech
About to remove:

 * RemoteTech

Continue? [Y/N]

Unhandled Exception: System.InvalidOperationException: Cannot read keys when eit        her application does not have a console or when console input has been redirecte        d from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at CKAN.User.YesNoDialogConsole(String text)
   at CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods)
   at CKAN.CmdLine.MainClass.Remove(RemoveOptions options)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

All other commands seem to behave identically when run under bash/mintty and when run in a Windows command prompt. This is running on a 64 bit Windows 7 Professional installation, with SP1 and all updates installed.

### PR DESCRIPTION
**Pull request by politas**
Console.WindiwWidth command was throwing an exception. Right-padding was not utilised on any other command, so code removed.

Moved available command into its own Action/Available.cs to match other commands.
Closes #359

### CODE REVIEW

**Comment by ayan4m1** [comment]
Will review this before the new year - sorry for the delay!

**Comment by Sxderp** [comment]
I don't suppose someone can provide a compiled binary. I'll test to ensure it fixes the issue. Looking at the code it looks like this should resolve the issue, but always good to run tests.

**Comment by politas** [comment]
It's guaranteed to not throw that particular exception error, but I suppose it could introduce a new problem. 

[Here you go](https://dl.dropboxusercontent.com/u/10499401/%231966/ckan.exe)

**Comment by Sxderp** [comment]
Looks good, I haven't run into any unforeseen issues.

**Comment by politas** [comment]
Ok, well, that copy is rebased on the new release, so feel free to use it instead of downloading a fresh 1.22.0 release.

**Pull request merged**
