### PR TITLE
Reduce MinimumSize for main window to 1280x700

### LINKED ISSUE #1891: Allow CKAN to fit on smaller resolution screens
CKAN Version: v1.20.0

Linux/Ubuntu 14.04

Bottom of CKAN window is cut off for screens with vertical resolution lower than 990 pixels and window cannot be made smaller. This puts the Apply/Cancel buttons off the screen for the most common screen resolution of 1366x768 ([source](http://www.rapidtables.com/web/dev/screen-resolution-statistics.htm))

### PR DESCRIPTION
**Pull request by politas**
I've been trying to figure out a way to write a unit test for this, since it's pretty easy for this to get clobbered by someone using the forms designer.

Closes #1891

### CODE REVIEW

**Comment by politas** [comment]
Also tried to move KSPVersionLabel into the Status bar, but it appears that is not showing up at all.

**Comment by Postremus** [comment]
[image: Inline-Bild 1]

2016-09-10 11:58 GMT+02:00 Myk <notifications@github.com>:

**Comment by politas** [comment]
@techman83, has anything changed with Travis in the last day?

**Comment by techman83** [comment]
@politas nothing [recently](http://changelog.travis-ci.com/) that I'm across. What was the drama?

**Comment by politas** [comment]
The build was failing with weird errors. All good, now.

**Comment by politas** [comment]
OK, the KSP version label is gone completely. It has caused a lot of grief due to complicated layout details, so I'm not sad to see it go. It might be nice to get those details in the status bar as well as (or instead of) in the window title.

**Comment by ayan4m1** [comment]
Looks good to me, thanks!

**Pull request merged**
