### PR TITLE
Background worker error

### PR DESCRIPTION
**Pull request by RichardLake**
Should prevent TargetInvocationException from being thrown by the background workers which will aid user support. Also moved the update repo handing out of the DoWork and into the RunWorkerCompleted due to style concerns. This is more a matter of style

### CODE REVIEW

**Comment by pjf** [comment]
In what cases were a TargetInvocationException being thrown? (Ie: How should I be testing this?)

**Comment by RichardLake** [comment]
Any case with an uncaught exception in the BackgroundWorker.DoWork should trigger it. The ones I knew about have been fixed in #1150 so this PR is a precaution in case the core starts throwing new exceptions.

**Comment by pjf** [comment]
A merge-conflict resolved copy of this is in #1290. Merging that will also close this PR.

**Comment by pjf** [comment]
Closing this as it's a subset of #1290.

**Pull request closed without merging**
