### PR TITLE
Deselect all/select installed

### PR DESCRIPTION
**Pull request by martinnj**
- Buttons on main form is moved to a dropdown menu for declutter.
 - Now using registry to only traverse installed mods, not all available when selecting.
 - Adding a toggle to the recommendations page to address #1148

### CODE REVIEW

**Comment by Postremus** [comment]
The caption of the checkbox should be on the suggested page ".. Sugested Mods".

**Comment by martinnj** [comment]
Took "recommended" from the tap page name, but it's corrected now.

**Comment by Postremus** [comment]
Would you please rebase your pr?

**Comment by martinnj** [comment]
I've been busy with some work so haven't looked at this in a while. Sorry. It looks like I severely messed up my fork of the project. The changes I made is minor so it'll be easier for me to fork again and redo the work.

**Comment by martinnj** [comment]
I've cleaned up my stuff, it's in a new PR: https://github.com/KSP-CKAN/CKAN/pull/1258 - Again, sorry for the mess.

**Comment by Postremus** [comment]
nothing to worry about. :)

**Pull request closed without merging**
