### PR TITLE
Adds a deselect all button and a select installed button.

### LINKED ISSUE #1148: (De)select all button
It would be useful to have a button to select/deselect all the mods on the recommend and suggests screens.

### PR DESCRIPTION
**Pull request by martinnj**
fixes #1148

### CODE REVIEW

**Comment by RichardLake** [comment]
Code looks good and it tests fine.

**Comment by pjf** [comment]
Drat, at least on mono 3.2.8 this causes a serious bug where ticking any box can cause an endless stream of exceptions:

```
CKAN.Main/<ModList_CellValueChanged>c__async0&) <0x0004f>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x0017f>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.Main._MarkModForInstall (string,bool) <0x001bf>
  at CKAN.Main/<MarkModForInstall>c__AnonStorey12.<>m__0 () <0x0001f>
  at CKAN.Util.Invoke<T> (T,System.Action) <0x000eb>
  at CKAN.Main.MarkModForInstall (string,bool) <0x00167>
  at CKAN.Main/<ModList_CellValueChanged>c__async0.MoveNext () <0x00563>
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<CKAN.Main/<ModList_CellValueChanged>c__async0> (CKAN.Main/<ModList_CellValueChanged>c__async0&) <0x0004f>
...
```

`git bisect` reveals that 84b5b497c59a27d6d0741ba50333cf265f26139f is the commit in question that first introduced this behaviour.

@martinnj : I may have to undo these commits for release, but we definitely *do* want your functionality. Mono 3.2.8 is a pain in terms of the bugs it has in the GUI. :(

**Comment by martinnj** [comment]
@pjf - Most of what is in this pull request is supposed to be replaced in [#1216](https://github.com/KSP-CKAN/CKAN/pull/1216). Seeing as how the buttons made it exceptionally cluttered and the functionality was missing from the recommendations page. I'll see if I can get an environment set up on my Mint machine and try things out with Mono instead of .NET.

**Comment by Postremus** [comment]
was able to reproduce it on .net, too.
will provide a metapackage for testing soon.

**Comment by Postremus** [comment]
http://puu.sh/iHYMR/3db8097125.ckan

**Comment by martinnj** [comment]
I assume I would need KSP 1.0.3 or 1.0.2 for this, I get this error from the ckan file:
`Module TweakableEverything required, but not listed in index, or not available for your version of KSP`

But you get the error simply checking/unchecking boxes in the ModList? Based on the fact that the trace comes out from `CKAN.Main.ModList_CellValueChanged`.

**Comment by Postremus** [comment]
@martinnj  already got a fix ready for this, pushing now.

**Pull request merged**
