### PR TITLE
small changes to column titles

### PR DESCRIPTION
**Pull request by vinix38**
I noticed that the "install/uninstall all" checkbox was moved upward, so I changed the text to a better version.
image
(that checkbox)
I also saw that there was a tooltip for that checkbox, is it possible to translate it? Or is it part of Core?
Note: some commits are redundant, as I haven't figured out how to compare against a pull request (still learning (: )

### CODE REVIEW

**Comment by HebaruSan** [comment]
Thanks! Added this to #3400 as well since it is branched off of that.

> I also saw that there was a tooltip for that checkbox, is it possible to translate it? Or is it part of Core?

Yes, it's possible, but it lives in a different file because WinForms treats tooltips as an afterthought:

https://github.com/KSP-CKAN/CKAN/blob/9bed12c3d3641ce2927c4a6d156b21b96e6e75da/GUI/Properties/Resources.resx#L431

> Note: some commits are redundant, as I haven't figured out how to compare against a pull request (still learning (: )

This wiki page has some suggestions for working with branches in git, in case you want to try it:

- https://github.com/KSP-CKAN/CKAN/wiki/Workflow#working-on-the-code-branches

In this case the "proper" thing would probably be to make your pull request here, using "git rebase" to connect it to the branch for #3400:

- https://github.com/HebaruSan/CKAN/tree/fix/download-labels

That way I would see it in my fork of the repo and be able to diff it against the current status of #3400, and after merging it would appear in #3400. But that may be kind of difficult, and this way works as well.

**Comment by vinix38** [comment]
I had forgotten this file, I'm going to make a tour of the history of all localized files to make sure I didn't forget anything

**Comment by HebaruSan** [comment]
> EDIT: for the filters in the search bar, will spaces create troubles? ("is:cached" --> "est: en cache")

Good question, yes, those should not contain spaces.

**Comment by HebaruSan** [comment]
Thanks for the updates, they've been added to #3400 as well. Is there anything remaining that you're planning to work on?

**Comment by vinix38** [comment]
I believe the French translation is now up to date, thank you :)

**Comment by HebaruSan** [comment]
Cool, this will ride along with #3400 then! Thanks again for the updates.

**Pull request closed without merging**
