### PR TITLE
Allow foss delisting

### PR DESCRIPTION
**Pull request by politas**
A proposed compromise solution to #1793

### CODE REVIEW

**Comment by Blu3wolf** [comment]
Thats no compromise, its negotiating with terrorists.

**Comment by ThomasKerman** [comment]
Thank you for your utterly useful comment. Have a nice day.

**Comment by passinglurker** [comment]
@Blu3wolf careful that's borderline godwin's law talk there.

Any way in the future a system like googles robot.txt included in mod zip files could be used to easily identify a maintainer or group of maintainers intentions to opt out or not.

**Comment by politas** [comment]
Rationale:

CKAN's policy was all about accessibility, and the rights of users. It was based on the assumption that all CKAN was doing was facilitating the installation of mods. Where it went wrong is in not taking into account the fact that in the minds of many CKAN users, CKAN also implicitly defines a support relationship, by linking to the "homepage" forum thread. We have attempted to disabuse users of that idea, but those efforts have been unsuccessful, and are likely to remain so, because people are people.

CKAN should not be in the position of effectively forcing a support relationship on people who are not willing to be part of one.

**Comment by politas** [comment]
@passinglurker You mean an opt-in opt-out method that doesn't involve a request to be added to the Opt-out list page I am creating with this PR?

The only issue I see with that is that embedding it in the the permanent download zip removes any ability to negotiate a change in stance.

**Comment by passinglurker** [comment]
@politas the advantage is the system can be consistently and reliably managed by a bot without haveing to worry about IDing the primary maintainer as long as the bot is pointed at an official download and every time there is an update the bot checks to see if the robot.txt equivalent has changed. 

and either way I don't see how that stops ckan from talking to the maintainers about addressing thier concerns and getting them to change thier minds

also if you are worried about edge cases where the maintainer accepts indexing but doesn't have time to reupload the mod with a different robot.txt equivalent then you can just offer to add them to an exceptions list so the bot can proceed I suppose.

**Comment by politas** [comment]
@passinglurker Ok, I see that could be a useful feature. At the moment, I am focused on what can be done immediately in processes and policy, without requiring time-consuming development work.

**Comment by passinglurker** [comment]
@politas yes I agree what can be done immediately should have priority I did say this was an idea for the future after all

**Comment by CliftonMarien** [comment]
I agree with this idea.

**Comment by passinglurker** [comment]
**I agree with this idea** _in case it wasn't obvious already_

**Comment by Cphoenix** [comment]
I've edited the [adding a mod guide](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN) to direct people to the opt-out-list.

**Comment by blowfishpro** [comment]
This seems very reasonable to me

**Comment by dewiniaid** [comment]
+1.  Though this it saddens me as a CKAN user to see this going on, I agree it's a necessary measure until a proper fix can be made on both the policy and technical levels.

**Comment by anxcon** [comment]
reasonable

**Comment by VaPaL** [comment]
Agree

**Comment by BobPalmer** [comment]
No surprise either, but I support this as well.  It ensures both parties have appropriate incentives to improve the process.

**Comment by pjf** [comment]
I'm hoping I can nit-pick the wording but (hopefully) not the intent here. Currently the change reads:

> It has become clear that in some cases, it is not possible to preserve mods with permissive licenses and have them remain under permissive licenses. Therefore, CKAN will not attempt to install permissively-licensed mods when the primary maintainer (or a significant group of maintainers if no single primary maintaner is easily identifiable) requests that the mod be taken off CKAN.

This is a little verbose, and also very specific. Can I suggest:

> In some cases it's not possible to install mods via the CKAN and maintain the goodwill of the author(s). The CKAN will not install any mod when the primary maintainer (or a significant group of maintainers when no primary is identifiable) requests the mod be removed from the CKAN.

This provides a consistent policy regardless of license, and provides the ability to request mod removal over a range of issues (eg: broken install, change of maintainer).

**Comment by BobPalmer** [comment]
Thanks pjf.

I think this policy, coupled with a staging repo (where either the authors, CKAN staff, or volunteers can test things out and sort out potential issues) will go a long way to making this a much better tool for all concerned (consumers, publishers, and creators).

**Comment by Blu3wolf** [comment]
concerned creators, perhaps. Consumers, not so much.

**Comment by BobPalmer** [comment]
I expect consumers will be better served by having access to mods again, and with folks working to improve the process than having mods pulled.  Again, thanks everyone for getting us to this point.  @pjf and team - where would be the best place to consolidate discussions about ongoing improvements (the staging area, maintainers, etc.)?

**Comment by Blu3wolf** [comment]
You realise you are talking about having access to mods again after ensuring there need not be any?

**Comment by pjf** [comment]
I'm hoping we can avoid re-discussing existing points, especially after there's already been such extensive conversations in #1793 and elsewhere.

@BobPalmer : With regards to staging areas, #1679 is an existing idea that's had some discussion. It'd be great to review and critique that, I haven't had a full chance to do so myself.

With regards to other discussions, I personally prefer a one-ticket-per-topic, because it means we can close out things when they're done, track changes against issues more effectively, and group them into milestones that are easier to manage. Having said that it's totally appropriate to have a discussion on improvements where new tickets are created as-needed when each idea gains speed.

**Comment by BobPalmer** [comment]
Sounds good.  I'll take a peek.

**Comment by mgsdk** [comment]
Agree

**Comment by linuxgurugamer** [comment]
agree

**Comment by TeddyDD** [comment]
Agree

**Comment by Cphoenix** [comment]
One suggestion for Opt-out-list.md : A "Reason" column could be useful so whomever is reading it would be able to tell if the situation has changed, and also make the distinction for cases like @BobPalmer 's where the opt-out isn't _completely_ opt-out, but rather a "I want to manage my own metadata, but it's okay that my mods are listed".

**Comment by anxcon** [comment]
agreed on the reason column, its information, information isn't bad, and helps new volunteers know if/when a reason is no longer valid

**Comment by TeddyDD** [comment]
"De-list" operation should be specified. Do we remove netkans? Or do we change just change extension to .froze so in case mod author would like to have his mods back on CKAN we have something to start with? Example: https://github.com/KSP-CKAN/NetKAN/pull/4294
What we do with .ckan files? Remove them or just hide by changing extension?

**Comment by anxcon** [comment]
@TeddyDD to clarify, would renaming the extension leave the future open to a "guide" popping up in forums equivalent to "run ckan.exe then type 1234 to see every mod plus the hidden ones" ?

**Comment by BobPalmer** [comment]
It's probably best to remove vs. just freeze tbh.

**Comment by BobPalmer** [comment]
Actually...  maybe offer a choice?  Freeze because they want it down while they sort stuff out, or remove completely because (for whatever reason) they do not wish to come back.

**Comment by TeddyDD** [comment]
@anxcon If you remove netkan you can still get it back using power of git so there is no difference at this point. Freezing netkans:
- makes easier to add mod back to CKAN
- makes easier to advanced ckan users to manually inflate netkan using netkan.exe and keep using mod from ckan. As I said it does not matter if you remove file or rename it. It is possible to get it back anyway. Renaming is just less annoying option.

**Comment by j-bos** [comment]
Also makes it clear that the mod is frozen and not just missing so much less likely to be readded by mistake . . .

**Comment by Cphoenix** [comment]
> Actually... maybe offer a choice? Freeze because they want it down while they sort stuff out, or remove completely because (for whatever reason) they do not wish to come back.

Freezing with the contents in place sounds like a good idea for the former case. When it comes to the latter, @politas has been removing the contents (just leaving the ID it used in the file as the only text, so it's not valid JSON) and then renaming it to .frozen. It removes the contents to there's no chance of something really weird happening and unintentionally having it be relisted (because the JSON deserialization attempt will fail), but it leaves a stub that's easy for anyone primarily using the GitHub browser UI to find the original data should the mod need to be relisted for any reason (author comes back, mod switches hands to a new author who wants to list it, etc.) so there's a starting point at least.

As @TeddyDD said, you can get it back via git anyway. I think the solution @politas has been using over the past few days is the best of both worlds.

**Comment by TeddyDD** [comment]
@Cphoenix could you explain me how to do this? Never heard of that method. I still prefer not removing file content ( I suppose bot ignore everything that has no .netkan extension right?)

**Comment by Cphoenix** [comment]
> @Cphoenix could you explain me how to do this? Never heard of that method. I still prefer to not removing file content ( I suppose bot ignore everything that has no .netkan extension right?)

https://github.com/KSP-CKAN/NetKAN/pull/4271/commits/db97a0423a019c8eb63d115d869f21a2a8e2c96d

Sorry I got that a little backward in my brain (this is what I get for not getting enough sleep :stuck_out_tongue_closed_eyes:  ). He's mostly just been renaming to .frozen , but I actually think this solution might be better. As far as I'm aware, yes, the bot ignores .frozen entirely. 

It's not really removing the data per-se. The old data is easy enough to get back by just reverting the commit that removed it. Just leaving the identifier in there though rather than valid JSON adds another layer of security. If by some fluke a bug is introduced in the bot and it tries to grab a .frozen file, it won't be able to use it, instead of the possibility of it silently failing.

I know I'm being nitpicky; it's a minor concern right now but just a thought.

**Comment by jrossignol** [comment]
You'll want to change my forum name on that list to nightingale. :wink:

**Comment by politas** [comment]
Thanks for that @jrossignol , I was going to chase that up .

**Comment by politas** [comment]
Here's what's been done so far:

CliftonM's .ckan files have been removed (though I kept backups), mainly because I merged his PR that did that, while all other files have been renamed to frozen (including the .netkan files for CliftonM's mods), which acts as a placeholder to signify that the names (and version numbers) have been used, while being ignored by the auto-indexing robot and CKAN client. My understanding is that the requests for removal have been more in protest than a genuine desire for permanent removal, so I took things out of the CKAN client' s awareness without wiping out the useful information they contain.

It is all temporary at this stage. Mods permanently delisted will have their .ckan files removed entirely and their .netkan files stripped of all content so they become name placeholders preventing duplication/confusion.

The intention of this change is that in the long run mods would stay in the listing, to allow autodetection  and downloading of the zip file, but no automated installation would be done, forcing users to open the zip file and manually install the contents. Until the code to handle that case is in place, de-listing is the only way to get the desired effect of not installing mods.

For Ferram's specific issues with FAR (and any other mods with similar concerns such as SVE), my proposed method would be changing the .netkan file to a specific download, disabling auto-indexing, and requiring a PR to be processed for each update, involving approval by the mod author or a designated maintainer.

**Comment by politas** [comment]
The opt-out list may need to have a "delegated approvers" column added at some stage.

**Comment by pjf** [comment]
Merging with thanks, although #1800 will be relevant to many on this thread.

My apologies that merging also automatically closes the ticket. You can continue to discuss policy and process on a closed pull-request, but do consider opening new issues as needed for those that need enduring visibility.

**Pull request merged**
