### PR TITLE
display all mod versions

### PR DESCRIPTION
**Pull request by grzegrzk**
Hi,

I have added tab that displays all versions of currently selected mod. It is displayed on ModInfo pane on the right - next to "Contents" tab.

It is displayed purely for informational reasons - user cannot force particular version installation or something like that.

Mod versions compatible with current KSP are highlighted.

About changes in code:
- I have added new UserControl: MainAllModVersions 
- I have refactored Main.Designer.cs & MainModInfo.cs.  Now MainModInfo.cs is separate UserControl instead of being partial of Main class. I was unable to layout controls properly without Visual Designer and when I try to use it on Main form it destroys layout. Now MainModInfo can be used with visual designer so it is easier to work with it.

### CODE REVIEW

**Comment by politas** [comment]
I didn't realise this was a possibility! Now I'm wondering if MainModList can similarly be separated out into a separate file to make the different UI elements easier to work with. I may have to get myself a Windows VM so I can load up VisualStudio

**Comment by grzegrzk** [comment]
> I didn't realise this was a possibility! Now I'm wondering if MainModList can similarly be separated out into a separate file to make the different UI elements easier to work with. I may have to get myself a Windows VM so I can load up VisualStudio

I think it should be not a problem to separate each tab of main window into separate UserControl. Unfortunately I do not know any way to automate it so it requires some manual work. The benefit is that if somebody messes with .design.cs file preventing it to be modified in Visual Studio designer in the future the mess will be only in single file so it will be easier to fix :).

**Comment by politas** [comment]
Indeed. Unfortunately, this work can only be done by someone working in Visual Studio. I'd love to know how Visual Studio somehow remembers things that aren't in the designer.cs files, and why hand-coding them causes such problems

We do have a plan to move to a GTK# interface for improved cross-platform support at some stage (#1840), which as far as I can tell, involves completely recreating the UI. And I'm not sure that there is a Windows visual editor tool for GTK#. You seem far more familiar with UI development than most, so if you could weigh in on #1840, I'd appreciate it.

**Comment by techman83** [comment]
@politas try vscode. Ms has released a Linux version.

**Comment by politas** [comment]
>try vscode. Ms has released a Linux version.

As I understand it, that has none of the GUI editing stuff from Visual Studio.

**Comment by grzegrzk** [comment]
@politas 
Thx for merging.

> I'd love to know how Visual Studio somehow remembers things that aren't in the designer.cs files, and why hand-coding them causes such problems

I have been googling for this for a while and it seems that it doesn't remember things in any special place. It just tries to parse .design.cs files and arrange controls in Visual Designer basing on this parsing. It has some limited possibilities to understand some corner cases, though, so if somebody edits .design.cs files by hand it may be confused and mess things up. The only advice that I have found how to solve it is "do not edit .design.cs files by hand". Of course this is very difficult when developers work on diverse platforms.

>We do have a plan to move to a GTK# interface for improved cross-platform support at some stage (#1840), which as far as I can tell, involves completely recreating the UI. And I'm not sure that there is a Windows visual editor tool for GTK#. You seem far more familiar with UI development than most, so if you could weigh in on #1840, I'd appreciate it.

I will try to investigate it a little bit and provide some input but it is quite difficult topic.

**Comment by politas** [comment]
I've worked out what is causing the designer to revert the column name!

    this.UpdateCol.Name = "Update";

That will always revert the column and leave an unused "this.UpdateCol".
https://github.com/KSP-CKAN/CKAN/blob/master/GUI/Main.Designer.cs#L472-L478

**Pull request merged**
