### PR TITLE
The great repo merge.

### PR DESCRIPTION
**Pull request by RichardLake**
See https://github.com/KSP-CKAN/CKAN/issues/852

Also see https://github.com/RichardLake/CKAN/pull/1 as a example of how to transfer a old PR to the combined repo. I've moved the tests to a single solution - there was a lot of duplicated data and classes between them.

### CODE REVIEW

**Comment by pjf** [comment]
Holy smokes. I'm on a tram and won't have a chance to look at this until tomorrow, but your timing is amazing! 

My phone client seems to be choking on links and commits (including the example on how to move a or), so if you've time is there any chance I can ask for what steps you took to create this PR?

Combing tests is so incredibly appreciated I can't begin to properly give my thanks. When the repos were split it looked like the tests went with all of them, and stitching them back together was one of the tasks I was least looking forward to doing. :-)

**Comment by RichardLake** [comment]
Given the amount of commits that have occured since the split it is no wonder the phone client is having issues. 

To create this PR I followed the process in http://nuclearsquid.com/writings/subtree-merging-and-you/, created a new project file and moved the tests. 

I outlined how I moved the outstanding PR on the GUI branch to the combined repo in https://github.com/RichardLake/CKAN/pull/1.

**Comment by pjf** [comment]
@RichardLake: Aaah! RichardLake#1 was *also* causing issues in my phone client, but I've managed to take a look at it now and rebasing PRs is a solid plan. Running out the door again now, but this will be joyously on my sprint list tomorrow.

In case you haven't been told recently, you *totally* rock. <3

**Comment by RichardLake** [comment]
Actually I think the way I did my trial run before was better. I'll do that and see.

**Comment by RichardLake** [comment]
And done. Now git log --follow works.

**Comment by pjf** [comment]
So `git read-tree --prefix...` (which I totally didn't know about until today) *doesn't* preserve log history, but merge'n'move does?

**Comment by RichardLake** [comment]
Seems so.

**Comment by techman83** [comment]
:100: - Amazing work!

**Pull request merged**
