### PR TITLE
WIP: changeset recreation redo

### PR DESCRIPTION
**Pull request by Postremus**
Currently, once a user wants to install or remove a mod (ticks / unticks it), the whole modlist (event incompatible) is searched for mods the user wants to Change.
When conflicts are present, this search is done a second time.

We now just add or remove the mod from the current user requested changeset.
needed for #1268

### CODE REVIEW

**Comment by plague006** [comment]
````
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CKAN.MainModList.<ComputeChangeSetFromModList>d__12.MoveNext() in d:\gitshit\CKAN\GUI\MainModList.cs:line 375
````
Repro steps: Select 2 mods that conflict, un-select one of the mods. I used `Astronomer's Pack - Clouds` high and medium for testing. As a side note in case this is an additional bug both mods remain highlighted red regardless of having them both deselected.

**Comment by plague006** [comment]
I've thrown a couple hundred mod installs/removals and ~1k checkbox ticks/unticks with no obvious issues.

**Comment by pjf** [comment]
Great joy! I have found a bug! :)

Steps to reproduce:

1. Select any mod for update by ticking the update box next to it.
2. Observe that "apply changes" remains greyed out.

Expected behaviour: The user can update their mods. :)

I've also committed ad30745d8297f27e124dc6bf8cf1a810c0e29a72, which is just a bunch of extra documentation, so you should be able to fast-forward your branch to it (I've also included in that a note about what I think may also be a bug, and which may or may not be related to the can't-update problems we're seeing).

**Comment by pjf** [comment]
Using d6be7be and mono 3.2.8, I now get endless error scroll when I tick an update box:

```
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x0010f>
  at CKAN.Main/<ModList_CellValueChanged>c__async0.MoveNext () <0x0062b>
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<CKAN.Main/<ModList_CellValueChanged>c__async0> (CKAN.Main/<ModList_CellValueChanged>c__async0&) <0x0004f>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x0017f>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
  at System.Windows.Forms.DataGridViewCell.SetValue (int,object) <0x0021b>
  at System.Windows.Forms.DataGridViewCell.set_Value (object) <0x0002b>
  at CKAN.GUIMod.SetUpgradeChecked (System.Windows.Forms.DataGridViewRow,System.Nullable`1<bool>) <0x0010f>
  at CKAN.Main/<ModList_CellValueChanged>c__async0.MoveNext () <0x0062b>
  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<CKAN.Main/<ModList_CellValueChanged>c__async0> (CKAN.Main/<ModList_CellValueChanged>c__async0&) <0x0004f>
  at CKAN.Main.ModList_CellValueChanged (object,System.Windows.Forms.DataGridViewCellEventArgs) <0x0017f>
  at System.Windows.Forms.DataGridView.OnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00069>
  at System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x00020>
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.DataGridView.InternalOnCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0xffffffff>
  at System.Windows.Forms.DataGridViewElement.RaiseCellValueChanged (System.Windows.Forms.DataGridViewCellEventArgs) <0x0002f>
```

I know this is a mono bug we've seen before, but I can't remember the exact cause (changing a box to the value it already has?).

**Comment by Postremus** [comment]
@pjf fixed.

**Comment by pjf** [comment]
Alas, updates are still giving me troubles. Using [my registry](https://dl.dropboxusercontent.com/u/9702672/KSP/registry-b77c7c8.json) I can hit the following bug:

1. Tick `Advanced Jet Engine` for upgrade.
2. Verify the mod is selected for upgrade in the Changeset.
3. Untick `Advanced Jet Engine` for upgrade.
4. Oh no! It's *still* in the changeset.

As far as I can tell, once a mod is ticked for upgrade it can't be unselected without clearing the whole changeset and starting again.

**Pull request closed without merging**
