### PR TITLE
Change Icon on FilterTool Button to something filter-y

### LINKED ISSUE #2009: Proposal: replace "Filter" button icon in the GUI from a looking glass to a filter
A looking glass icon is usually associated with search functionality, rather than filtering (I've never thought until recently that I could actually list all mods, including incompatible; I've just overlooked this function because of the "search" icon). Replacing it with an actual filter icon will make things clearer.

### PR DESCRIPTION
**Pull request by politas**
Replace the magnifying glass with something better  (I refuse to accept the funnel = filter idea)
filter
Closes #2009

### CODE REVIEW

**Comment by HebaruSan** [comment]
I'd like to help review, but there are conflicts now. Can you rebase?

**Comment by politas** [comment]
Rebased

**Comment by HebaruSan** [comment]
Can the old old search.png file be removed? I don't think it's being used anymore.

**Comment by politas** [comment]
Good point

**Comment by politas** [comment]
I'm tempted to leave it in, since it may come in useful in the future, and it's only 1493 bytes.

**Comment by HebaruSan** [comment]
I suppose it's not important, and the new icon definitely works fine. I'll take a stab at following the full merge process, including change log updates...

**Comment by politas** [comment]
We've been putting "Merge #<pr> Blah blah blah" as the comment on the Merge commit, to make the merge commits stand out in the history. Other than that, <3<3<3!!!!

**Comment by HebaruSan** [comment]
That's a good idea; I've added it to the wiki's merging notes to help me remember for next time. Thanks!

**Pull request merged**
