### PR TITLE
Special comment on public-domain license in Spec.md

### PR DESCRIPTION
**Pull request by janbrohl**
PR for #1749

### CODE REVIEW

**Comment by politas** [comment]
This is a misapplication of public domain law. Works may revert to public domain in different jurisdictions earlier or later, but if an author places a work in the public domain, it is in the public domain everywhere. This change is unnecessary.

**Comment by dbent** [comment]
> This is a misapplication of public domain law. Works may revert to public domain in different jurisdictions earlier or later, but if an author places a work in the public domain, it is in the public domain everywhere. This change is unnecessary.

Not quite, believe it or not, in some jurisdictions it's basically impossible to relinquish copyright. That's why licenses like [CC0](https://creativecommons.org/about/cc0/) and the [Unlicense](http://unlicense.org/) exist. It's also why prominent public domain works like [SQLite](http://www.sqlite.org/copyright.html) have to have special licenses to deal with the fact.

>  Even though SQLite is in the public domain and does not require a license, some users want to obtain a license anyway. Some reasons for obtaining a license include:
>  - You are using SQLite in a jurisdiction that does not recognize the public domain.
>  - You are using SQLite in a jurisdiction that does not recognize the right of an author to dedicate their work to the public domain.

However, I agree that *intent* is what we're signalling with `public-domain`. If we go by the requirement that a work has to be public domain *everywhere* to be `public-domain` then we'll *never* use `public-domain` because no mod created for KSP would ever fulfill that criteria, at least for the next hundred years or so.

**Comment by plague006** [comment]
> For a one-time fee of US $6000.00 we will add your company name and contact information to a copy of the sample license agreement, sign the completed license, and send you the original signed copy by post and a scan of the signed document by email.

TIL public domain software is hella expensive (to get a license for).

**Comment by politas** [comment]
I am unconvinced that any jurisdictions that do not recognise the public domain, or an author's right to dedicate their work to the public domain actually exist.

**Comment by janbrohl** [comment]
@politas 

There is a reason why licenses like [CC0](https://creativecommons.org/about/cc0/) exist (see [CC on PD](https://creativecommons.org/about/pdm/) )

Also have a look at https://en.wikipedia.org/wiki/Public-domain_software from which I took this quote:
```
In some Jurisdictions, some rights (in particular moral rights) cannot be disclaimed: 
for instance, civil law tradition-based German law's "Urheberrecht" differs here from the Anglo-saxon common law tradition's "copyright" concept.
```

**Comment by plague006** [comment]
The US is the easiest country to find documentation on because of the nature of the internet. So here are a bunch of articles talking about how unclear it is how or even if one can release their copy rights. 

https://www.publicknowledge.org/news-blog/blogs/lets-make-it-easier-to-expand-the-public-domain

https://www.techdirt.com/articles/20150123/15564629797/why-we-still-cant-really-put-anything-public-domain-why-that-needs-to-change.shtml

https://opensource.org/faq#public-domain

To mix it up, this source says you *can* relinquish rights in the US and Europe but doesn't really touch on any other regions: https://cr.yp.to/publicdomain.html

**Comment by plague006** [comment]
Ultimately, abandoning rights and the public domain in general is messy and we're not lawyers so why not have a little caveat/disclaimer included?

**Comment by politas** [comment]
Because it's utterly pointless. Who is ever going to dispute any of this? Who is going to claim copyright protections on game mods they clearly intended to release into the public domain?

**Comment by janbrohl** [comment]
Maybe it really is pointless as the licenses in the index do not have to match those in the archives anyway and are only hints to what the actual license might be.

**Comment by janbrohl** [comment]
Was a pointless attempt to make license info more reliable

**Pull request closed without merging**
