### PR TITLE
A new translation of Resources.zh-CN.resx

### PR DESCRIPTION
**Pull request by zhouyiqing0304**
翻译语言 简体中文 zh-CN

此更新使用了更加简洁、有效、通俗易懂的语言，并将原本有语病的语言进行了修改，使翻译更准确，避免误解。 此更新是在原有的基础上和CKAN的使用上进行的改进，所以修改不是很大。
我是手动翻译，非机翻，所以很难有翻译问题。
请管理员（作者也行）通过这个申请，谢谢。

___

Via Google Translate:

Translation language Simplified Chinese zh-CN

This update uses more concise, effective, and easy-to-understand language, and modifies the original language with grammatical errors to make the translation more accurate and avoid misunderstandings. This update is an improvement on the original basis and the use of CKAN, so the modification is not very large.
I translated manually, not by machine, so it is unlikely to have translation problems.
Please approve this application, administrator (author is also OK), thank you.

### CODE REVIEW

**Comment by zhouyiqing0304** [comment]
@HebaruSan I paid a lot on this. Have a look.

**Review by HebaruSan — APPROVED** [review]
I can't vouch for whether these are more idiomatic or easier to understand, but pasting a random selection of them into Google Translate, they do seem to be either equivalent or improvments. Thanks very much for the update!

**Comment by zhouyiqing0304** [comment]
Thank you for taking my advice.
Google translate isn't a good tool. If you understand Chinese, watch this video: https://www.bilibili.com/video/BV1vs421N7XV

**Comment by zhouyiqing0304** [comment]
I think ChatGPT is better(still not better than me)

**Comment by HebaruSan** [comment]
> Thank you for taking my advice.

Thank you for contributing! If you have any interest in doing more, we usually encourate translators to use this site, as it's a bit easier than editing XML files by hand:

https://crowdin.com/project/ckan

> If you understand Chinese, watch this video

I don't understand Chinese, otherwise I would be editing these strings myself.

**Pull request merged**
